apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app":"api-zip-s3","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"api-zip-s3","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"test","component":"rbac","environment":"mmjc-test"},"name":"test-api-zip-s3","namespace":"mmjc-test"},"rules":[{"apiGroups":[""],"resources":["configmaps","secrets"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["pods"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2025-10-27T06:50:23Z"
  labels:
    app: api-zip-s3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-zip-s3
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: test
    component: rbac
    environment: mmjc-test
  name: test-api-zip-s3
  namespace: mmjc-test
  resourceVersion: "53778636"
  uid: 065720be-bb38-4008-b5de-41789308ce34
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
