apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
  creationTimestamp: "2025-07-31T08:33:14Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: minio
    release: milvus-mmjc-test
  name: export-milvus-mmjc-test-minio-0
  namespace: mmjc-test
  resourceVersion: "22654769"
  uid: 443566f1-e1a8-410b-ac21-687663b08f45
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
  volumeName: pvc-443566f1-e1a8-410b-ac21-687663b08f45
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
