apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
  creationTimestamp: "2025-07-31T08:33:14Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: minio
    release: milvus-mmjc-test
  name: export-milvus-mmjc-test-minio-3
  namespace: mmjc-test
  resourceVersion: "22654804"
  uid: 91b15ff3-a2b4-4861-a6a6-21e33664867b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
  volumeName: pvc-91b15ff3-a2b4-4861-a6a6-21e33664867b
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
