apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Example overlay for using Artifactory registry
# Apply with: kubectl apply -k kustomize/overlays/artifactory/

bases:
  - ../../mmjc-test

namespace: mmjc-test

# Override images to use Artifactory registry
images:
  # ICR custom images -> Artifactory
  - name: icr.io/mjc-cr/mmjc-agents
    newName: br.icr.io/br-ibm-images/mmjc-agents
    newTag: 0.0.2

  - name: icr.io/mjc-cr/mmjc-frontend
    newName: br.icr.io/br-ibm-images/mmjc-frontend
    newTag: 0.0.2

  - name: icr.io/mjc-cr/mmjc-po
    newName: br.icr.io/br-ibm-images/mmjc-po
    newTag: 0.0.2

  - name: icr.io/mjc-cr/go-mcp-git-s3
    newName: br.icr.io/br-ibm-images/go-mcp-git-s3
    newTag: 1.0.31

  - name: icr.io/mjc-cr/mcp-milvus-db
    newName: br.icr.io/br-ibm-images/mcp-milvus-db
    newTag: 0.0.2

  - name: icr.io/mjc-cr/mjc-mermaid-validator
    newName: br.icr.io/br-ibm-images/mjc-mermaid-validator
    newTag: 1.0.17-llm-ready-amd64

  # External images remain the same (or mirror them too)
  - name: ghcr.io/ibm/mcp-context-forge
    newName: ghcr.io/ibm/mcp-context-forge
    newTag: 0.6.0

  - name: milvusdb/milvus
    newName: milvusdb/milvus
    newTag: v2.5.15

  - name: zilliz/attu
    newName: zilliz/attu
    newTag: v2.5.6
