apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
  creationTimestamp: "2025-10-02T11:39:28Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: valkey
  name: data-valkey-0
  namespace: mmjc-dev
  resourceVersion: "44771074"
  uid: 0c404765-1436-4cce-918f-dc63c75a0cbc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
  volumeName: pvc-0c404765-1436-4cce-918f-dc63c75a0cbc
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
