apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
  creationTimestamp: "2025-07-31T07:12:24Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/name: kafka
  name: data-milvus-mmjc-dev-kafka-1
  namespace: mmjc-dev
  resourceVersion: "22634598"
  uid: 82893e6f-3034-4e78-b033-ef30727379a9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
  volumeName: pvc-82893e6f-3034-4e78-b033-ef30727379a9
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
