apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"pv.kubernetes.io/bind-completed":"yes","pv.kubernetes.io/bound-by-controller":"yes","volume.beta.kubernetes.io/storage-provisioner":"vpc.file.csi.ibm.io","volume.kubernetes.io/storage-provisioner":"vpc.file.csi.ibm.io"},"creationTimestamp":"2025-06-16T13:57:37Z","finalizers":["kubernetes.io/pvc-protection"],"labels":{"app":"redis-cluster"},"name":"data-redis-cluster-dev-0","namespace":"mmjc-dev","resourceVersion":"10751304","uid":"07b344b1-b1e6-488f-9b54-93cbd0d44cbd"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"20Gi"}},"storageClassName":"ibmc-vpc-file-1000-iops","volumeMode":"Filesystem","volumeName":"pvc-07b344b1-b1e6-488f-9b54-93cbd0d44cbd"},"status":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"20Gi"},"phase":"Bound"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: vpc.file.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.file.csi.ibm.io
  creationTimestamp: "2025-06-16T13:57:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: redis-cluster
  name: data-redis-cluster-dev-0
  namespace: mmjc-dev
  resourceVersion: "11715211"
  uid: 07b344b1-b1e6-488f-9b54-93cbd0d44cbd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-vpc-file-1000-iops
  volumeMode: Filesystem
  volumeName: pvc-07b344b1-b1e6-488f-9b54-93cbd0d44cbd
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
