apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
  creationTimestamp: "2025-07-31T07:12:24Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: minio
    release: milvus-mmjc-dev
  name: export-milvus-mmjc-dev-minio-3
  namespace: mmjc-dev
  resourceVersion: "22634729"
  uid: b70c1121-609a-400d-8829-b6119583c2f1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
  volumeName: pvc-b70c1121-609a-400d-8829-b6119583c2f1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
