apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
  creationTimestamp: "2025-07-09T08:31:55Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    component: triggerer
    release: airflow-mmjc-dev
    tier: airflow
  name: logs-airflow-mmjc-dev-triggerer-0
  namespace: mmjc-dev
  resourceVersion: "16450243"
  uid: 2fd08484-0fe0-4256-ac26-78a97a68fc4e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
  volumeName: pvc-2fd08484-0fe0-4256-ac26-78a97a68fc4e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  phase: Bound
