apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
  creationTimestamp: "2025-10-14T19:32:04Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: arc-extractor
  name: source-data-arc-extractor-0
  namespace: mmjc-dev
  resourceVersion: "49279900"
  uid: 8a4d117f-dbdb-4eda-9176-d3434d104515
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
  volumeName: pvc-8a4d117f-dbdb-4eda-9176-d3434d104515
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
