# ⚠️  WARNING: This is a TEMPLATE - NOT for production use
# All sensitive data has been replaced with placeholders
# Replace all <REPLACE_WITH_BASE64_ENCODED_*> values before applying
#
# Original: mmjc-test/secrets/openai-api-key-agents.yaml
# Templated: Fri Oct 31 21:15:02 -03 2025
#
apiVersion: v1
data:
  OPENAI_API_KEY: <REPLACE_WITH_BASE64_ENCODED_OPENAI_API_KEY>
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: <REMOVED_CONTAINED_PLAINTEXT_SECRETS>
  name: openai-api-key-agents
  namespace: mmjc-test
type: Opaque
