apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-test
    meta.helm.sh/release-namespace: mmjc-test
  creationTimestamp: "2025-07-31T08:33:13Z"
  labels:
    app.kubernetes.io/instance: milvus-mmjc-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-6.3.3
  name: milvus-mmjc-test-etcd
  namespace: mmjc-test
  resourceVersion: "22654230"
  uid: 718f7716-dda0-4897-8839-600777d97123
spec:
  clusterIP: 172.21.254.158
  clusterIPs:
  - 172.21.254.158
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: client
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: peer
  selector:
    app.kubernetes.io/instance: milvus-mmjc-test
    app.kubernetes.io/name: etcd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
