apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-test
    meta.helm.sh/release-namespace: mmjc-test
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: "2025-07-31T08:33:13Z"
  labels:
    app.kubernetes.io/instance: milvus-mmjc-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-6.3.3
  name: milvus-mmjc-test-etcd-headless
  namespace: mmjc-test
  resourceVersion: "22654223"
  uid: 4734b10b-11fe-4840-bd7b-bf463ff88a9f
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: client
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: peer
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: milvus-mmjc-test
    app.kubernetes.io/name: etcd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
