apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-service-test","namespace":"mmjc-test"},"spec":{"ports":[{"name":"redis","port":6379,"targetPort":6379}],"selector":{"app":"redis-cluster"},"type":"ClusterIP"}}
  creationTimestamp: "2025-06-16T14:01:09Z"
  name: redis-service-test
  namespace: mmjc-test
  resourceVersion: "10751817"
  uid: 28590d6b-7c45-47ed-a056-5f6a0dc8e5e5
spec:
  clusterIP: 172.21.119.180
  clusterIPs:
  - 172.21.119.180
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-cluster
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
