apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'code-analysis-api'
        static_configs:
          - targets: ['code-analysis-api:9090']
        metrics_path: /metrics
        scrape_interval: 10s
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\n\nscrape_configs:\n  - job_name: 'code-analysis-api'\n    static_configs:\n      - targets: ['code-analysis-api:9090']\n    metrics_path: /metrics\n    scrape_interval: 10s\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"code-analysis-api","app.kubernetes.io/version":"dev","component":"monitoring","environment":"dev","managed-by":"kustomize"},"name":"code-analysis-monitoring","namespace":"mmjc-dev"}}
  creationTimestamp: "2025-10-30T05:15:00Z"
  labels:
    app: code-analysis-api
    app.kubernetes.io/version: dev
    component: monitoring
    environment: dev
    managed-by: kustomize
  name: code-analysis-monitoring
  namespace: mmjc-dev
  resourceVersion: "54772400"
  uid: f824b640-da35-4f48-9683-a22c3494a7eb
