apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: airflow-test
    meta.helm.sh/release-namespace: airflow-test
  creationTimestamp: "2025-07-14T10:31:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.17.0
    component: worker
    heritage: Helm
    release: airflow-test
    tier: airflow
  name: airflow-test-worker
  namespace: airflow-test
  resourceVersion: "17792649"
  uid: fb58a80e-21de-4b2d-b00a-e3c7bf53e286
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: worker-logs
    port: 8793
    protocol: TCP
    targetPort: 8793
  selector:
    component: worker
    release: airflow-test
    tier: airflow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
