apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'mcp-git-s3-server'
      static_configs:
      - targets: ['mcp-git-s3-server:8080']
      metrics_path: /metrics
      scrape_interval: 10s
      scrape_timeout: 5s

    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
kind: ConfigMap
metadata:
  annotations:
    app.kubernetes.io/description: High-performance MCP Git-S3 Tools Server
    app.kubernetes.io/documentation: https://github.com/your-org/java-mcp-tool-s3git
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\n\nscrape_configs:\n- job_name: 'mcp-git-s3-server'\n  static_configs:\n  - targets: ['mcp-git-s3-server:8080']\n  metrics_path: /metrics\n  scrape_interval: 10s\n  scrape_timeout: 5s\n\n- job_name: 'kubernetes-pods'\n  kubernetes_sd_configs:\n  - role: pod\n  relabel_configs:\n  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n    action: keep\n    regex: true\n  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]\n    action: replace\n    target_label: __metrics_path__\n    regex: (.+)\n  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]\n    action: replace\n    regex: ([^:]+)(?::\\d+)?;(\\d+)\n    replacement: $1:$2\n    target_label: __address__\n"},"kind":"ConfigMap","metadata":{"annotations":{"app.kubernetes.io/description":"High-performance MCP Git-S3 Tools Server","app.kubernetes.io/documentation":"https://github.com/your-org/java-mcp-tool-s3git","deployment.kubernetes.io/revision":"1"},"labels":{"app":"mcp-git-s3-server","app.kubernetes.io/component":"api-server","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"mcp-git-s3-server","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"0.0.1-SNAPSHOT","component":"monitoring"},"name":"mcp-git-s3-monitoring","namespace":"mmjc-test"}}
  creationTimestamp: "2025-06-16T11:56:38Z"
  labels:
    app: mcp-git-s3-server
    app.kubernetes.io/component: api-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mcp-git-s3-server
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    component: monitoring
  name: mcp-git-s3-monitoring
  namespace: mmjc-test
  resourceVersion: "10730974"
  uid: 9f88e692-1f22-4519-80ca-c76e45042206
