apiVersion: v1
data:
  setup.sh: |-
    #!/bin/bash

    ID="${MY_POD_NAME#"milvus-mmjc-test-kafka-"}"
    if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
        export KAFKA_CFG_BROKER_ID="$(grep "broker.id" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')"
    else
        export KAFKA_CFG_BROKER_ID="$((ID + 0))"
    fi

    exec /entrypoint.sh /run.sh
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-test
    meta.helm.sh/release-namespace: mmjc-test
  creationTimestamp: "2025-07-31T08:33:13Z"
  labels:
    app.kubernetes.io/instance: milvus-mmjc-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-15.5.1
  name: milvus-mmjc-test-kafka-scripts
  namespace: mmjc-test
  resourceVersion: "22654221"
  uid: b1a68c64-cd61-421b-9b61-7225afc3d7b0
