apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow-test

resources:
  # Deployments
  - deployments/api-server.yaml
  - deployments/dag-processor.yaml
  - deployments/scheduler.yaml
  - deployments/statsd.yaml

  # StatefulSets
  - statefulsets/triggerer.yaml
  - statefulsets/worker.yaml

  # Services
  - services/api-server.yaml
  - services/statsd.yaml
  - services/triggerer.yaml
  - services/worker.yaml

  # ConfigMaps
  - configmaps/airflow-config.yaml
  - configmaps/statsd-config.yaml

  # PVCs
  - pvcs/logs-triggerer-0.yaml
  - pvcs/logs-worker-0.yaml
  - pvcs/dags.yaml

# Image transformations - Modify these to change registry/prefix
images:
  # ICR images
  - name: icr.io/mjc-cr/mmjc-airflow-service
    newName: icr.io/mjc-cr/mmjc-airflow-service
    newTag: latest

  # Quay.io images
  - name: quay.io/prometheus/statsd-exporter
    newName: quay.io/prometheus/statsd-exporter
    newTag: v0.28.0

# Common labels to add to all resources
commonLabels:
  environment: test
  managed-by: kustomize
