apiVersion: v1
data:
  init-certs.sh: '#!/bin/bash'
  setup.sh: |-
    #!/bin/bash

    # Execute entrypoint as usual after obtaining ZOO_SERVER_ID
    # check ZOO_SERVER_ID in persistent volume via myid
    # if not present, set based on POD hostname
    if [[ -f "/bitnami/zookeeper/data/myid" ]]; then
        export ZOO_SERVER_ID="$(cat /bitnami/zookeeper/data/myid)"
    else
        HOSTNAME="$(hostname -s)"
        if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
            ORD=${BASH_REMATCH[2]}
            export ZOO_SERVER_ID="$((ORD + 1 ))"
        else
            echo "Failed to get index from hostname $HOST"
            exit 1
        fi
    fi
    exec /entrypoint.sh /run.sh
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-test
    meta.helm.sh/release-namespace: mmjc-test
  creationTimestamp: "2025-07-31T08:33:13Z"
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: milvus-mmjc-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-8.1.2
  name: milvus-mmjc-test-zookeeper-scripts
  namespace: mmjc-test
  resourceVersion: "22654220"
  uid: dc0473a2-fba9-4a9e-9d0d-8a0b4b05698b
