apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-test
    meta.helm.sh/release-namespace: mmjc-test
  creationTimestamp: "2025-07-31T08:33:14Z"
  generation: 5
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-8.0.17
    heritage: Helm
    release: milvus-mmjc-test
  name: milvus-mmjc-test-minio
  namespace: mmjc-test
  resourceVersion: "22710086"
  uid: 5aee9af1-7b83-4991-8521-cfbd85e48eac
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
      release: milvus-mmjc-test
  serviceName: milvus-mmjc-test-minio-svc
  template:
    metadata:
      annotations:
        checksum/config: 79423988cb4463840fcb674e896856b4a10be9d1a99bab416be480b467d59eb5
        checksum/secrets: 5d097ca68ddb8f1a14ac8260c9f2bb1fbb2280b7ceafefdc79820958c48844c0
      creationTimestamp: null
      labels:
        app: minio
        release: milvus-mmjc-test
      name: milvus-mmjc-test-minio
    spec:
      containers:
      - command:
        - /bin/sh
        - -ce
        - /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server  http://milvus-mmjc-test-minio-{0...3}.milvus-mmjc-test-minio-svc.mmjc-test.svc.cluster.local/export
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: milvus-mmjc-test-minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: milvus-mmjc-test-minio
        image: minio/minio:RELEASE.2024-05-28T17-19-04Z
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /minio/health/live
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: minio
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /export
          name: export
      dnsPolicy: ClusterFirst
      nodeSelector:
        ibm-cloud.kubernetes.io/worker-pool-name: milvus-pool
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccount: milvus-mmjc-test-minio
      serviceAccountName: milvus-mmjc-test-minio
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: reserved
        operator: Equal
        value: milvus
      volumes:
      - name: minio-user
        secret:
          defaultMode: 420
          secretName: milvus-mmjc-test-minio
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: export
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 4
  collisionCount: 0
  currentReplicas: 4
  currentRevision: milvus-mmjc-test-minio-5cfc5d6489
  observedGeneration: 5
  readyReplicas: 4
  replicas: 4
  updateRevision: milvus-mmjc-test-minio-5cfc5d6489
  updatedReplicas: 4
