apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    app.kubernetes.io/description: High-performance MCP Git-S3 Tools Server
    app.kubernetes.io/documentation: https://github.com/your-org/java-mcp-tool-s3git
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{"app.kubernetes.io/description":"High-performance MCP Git-S3 Tools Server","app.kubernetes.io/documentation":"https://github.com/your-org/java-mcp-tool-s3git","deployment.kubernetes.io/revision":"1"},"labels":{"app":"mcp-git-s3-server","app.kubernetes.io/component":"api-server","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"mcp-git-s3-server","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"0.0.1-SNAPSHOT","component":"rbac"},"name":"mcp-git-s3-server","namespace":"mmjc-test"}}
  creationTimestamp: "2025-06-16T11:56:36Z"
  labels:
    app: mcp-git-s3-server
    app.kubernetes.io/component: api-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mcp-git-s3-server
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    component: rbac
  name: mcp-git-s3-server
  namespace: mmjc-test
  resourceVersion: "10730966"
  uid: e2dbe268-239c-43fa-ad80-ebbd9c457342
