apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"api-zip-s3","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"api-zip-s3","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"test","component":"rbac","environment":"mmjc-test"},"name":"test-api-zip-s3","namespace":"mmjc-test"}}
  creationTimestamp: "2025-10-27T06:50:22Z"
  labels:
    app: api-zip-s3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-zip-s3
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: test
    component: rbac
    environment: mmjc-test
  name: test-api-zip-s3
  namespace: mmjc-test
  resourceVersion: "53778633"
  uid: 55c0e8fe-216a-417e-aca5-64ec6bde16d9
