# ⚠️  WARNING: This is a TEMPLATE - NOT for production use
# All sensitive data has been replaced with placeholders
# Replace all <REPLACE_WITH_BASE64_ENCODED_*> values before applying
#
# Original: airflow-test/secrets/airflow-test-fernet-key.yaml
# Templated: Fri Oct 31 21:15:01 -03 2025
#
apiVersion: v1
data:
  fernet-key: <REPLACE_WITH_BASE64_ENCODED_FERNET_KEY>
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    chart: airflow-1.17.0
    heritage: Helm
    release: airflow-test
    tier: airflow
  name: airflow-test-fernet-key
  namespace: airflow-test
type: Opaque
