# ⚠️  WARNING: This is a TEMPLATE - NOT for production use
# All sensitive data has been replaced with placeholders
# Replace all <REPLACE_WITH_BASE64_ENCODED_*> values before applying
#
# Original: airflow-test/secrets/cos-mmjc-airflow-secret.yaml
# Templated: Fri Oct 31 21:15:01 -03 2025
#
apiVersion: v1
data:
  access-key: <REPLACE_WITH_BASE64_ENCODED_ACCESS_KEY>
  secret-key: <REPLACE_WITH_BASE64_ENCODED_SECRET_KEY>
kind: Secret
metadata:
  name: cos-mmjc-airflow-secret
  namespace: airflow-test
type: ibm/ibmc-s3fs
