apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "81"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"agents-mmjc-test","namespace":"mmjc-test"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"agents-mmjc"}},"strategy":{"rollingUpdate":{"maxSurge":0,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"labels":{"app":"agents-mmjc"}},"spec":{"containers":[{"env":[{"name":"API_AUTH_TOKENS","valueFrom":{"secretKeyRef":{"key":"API_AUTH_TOKENS","name":"api-auth-tokens-agents"}}},{"name":"MODEL_NAME","value":"openai:sonnet-4-5"},{"name":"OPENAI_API_BASE","value":"https://model-gateway.llm-adapter-dev-c97c2ce0266e6f32de317d52e2a84f46-0001.us-east.containers.appdomain.cloud/v1"},{"name":"OPENAI_API_KEY","valueFrom":{"secretKeyRef":{"key":"OPENAI_API_KEY","name":"openai-api-key-agents"}}},{"name":"MCP_GATEWAY_URL","value":"http://mcp-gateway-test.mmjc-test.svc.cluster.local/servers/d22371abbe0042559ae52772ff3b9337/sse"},{"name":"MCP_GATEWAY_JWT_TOKEN","valueFrom":{"secretKeyRef":{"key":"jwt_token","name":"mcp-gateway-jwt-token"}}},{"name":"MERMAID_VALIDATOR_URL","value":"http://mermaid-validator-api.mmjc-test.svc.cluster.local/api/v1/validate"},{"name":"COS_ENDPOINT_URL","value":"https://s3.us-south.cloud-object-storage.appdomain.cloud"},{"name":"COS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"S3_ACCESS_KEY","name":"s3-access-key-tools"}}},{"name":"COS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"S3_SECRET_KEY","name":"s3-secret-key-tools"}}},{"name":"MAX_THREADS","value":"10"},{"name":"GIT_USERNAME","value":"romanas-marcenko"},{"name":"GIT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"GIT_PASSWORD_SECRET","name":"git-password-secret-agents"}}},{"name":"POSTGRESQL_HOST","value":"7bce9b8c-e602-4ae6-8a44-ad87cc332d96.c9v3nahd0oekcvsra2t0.private.databases.appdomain.cloud"},{"name":"POSTGRESQL_PORT","value":"32337"},{"name":"POSTGRESQL_USERNAME","valueFrom":{"secretKeyRef":{"key":"POSTGRESQL_USERNAME","name":"postgresql-secret-test"}}},{"name":"POSTGRESQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRESQL_PASSWORD","name":"postgresql-secret-test"}}},{"name":"POSTGRESQL_DATABASE","value":"mmjc"},{"name":"POSTGRESQL_SSLMODE","value":"verify-full"}],"image":"icr.io/mjc-cr/mmjc-agents:0.0.2","imagePullPolicy":"Always","name":"agents","ports":[{"containerPort":8080,"name":"agents"}],"resources":{"limits":{"cpu":0.5,"memory":"2Gi"},"requests":{"cpu":0.25,"memory":"1Gi"}}}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}]}}}}
  creationTimestamp: "2025-06-16T12:53:44Z"
  generation: 102
  name: agents-mmjc-test
  namespace: mmjc-test
  resourceVersion: "55170337"
  uid: 2186e775-c52a-4561-8a23-c519649c3ce4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: agents-mmjc
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-31T11:26:21+02:00"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: agents-mmjc
    spec:
      containers:
      - env:
        - name: API_AUTH_TOKENS
          valueFrom:
            secretKeyRef:
              key: API_AUTH_TOKENS
              name: api-auth-tokens-agents
        - name: MODEL_NAME
          value: openai:sonnet-4-5
        - name: OPENAI_API_BASE
          value: https://model-gateway.llm-adapter-dev-c97c2ce0266e6f32de317d52e2a84f46-0001.us-east.containers.appdomain.cloud/v1
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_API_KEY
              name: openai-api-key-agents
        - name: MCP_GATEWAY_URL
          value: http://mcp-gateway-test.mmjc-test.svc.cluster.local/servers/d22371abbe0042559ae52772ff3b9337/sse
        - name: MCP_GATEWAY_JWT_TOKEN
          valueFrom:
            secretKeyRef:
              key: jwt_token
              name: mcp-gateway-jwt-token
        - name: MERMAID_VALIDATOR_URL
          value: http://mermaid-validator-api.mmjc-test.svc.cluster.local/api/v1/validate
        - name: COS_ENDPOINT_URL
          value: https://s3.us-south.cloud-object-storage.appdomain.cloud
        - name: COS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY
              name: s3-access-key-tools
        - name: COS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_KEY
              name: s3-secret-key-tools
        - name: MAX_THREADS
          value: "10"
        - name: GIT_USERNAME
          value: romanas-marcenko
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GIT_PASSWORD_SECRET
              name: git-password-secret-agents
        - name: POSTGRESQL_HOST
          value: 7bce9b8c-e602-4ae6-8a44-ad87cc332d96.c9v3nahd0oekcvsra2t0.private.databases.appdomain.cloud
        - name: POSTGRESQL_PORT
          value: "32337"
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRESQL_USERNAME
              name: postgresql-secret-test
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRESQL_PASSWORD
              name: postgresql-secret-test
        - name: POSTGRESQL_DATABASE
          value: mmjc
        - name: POSTGRESQL_SSLMODE
          value: verify-full
        - name: GUNICORN_TIMEOUT
          value: "1200"
        image: icr.io/mjc-cr/mmjc-agents:0.0.2
        imagePullPolicy: Always
        name: agents
        ports:
        - containerPort: 8080
          name: agents
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-29T07:56:36Z"
    lastUpdateTime: "2025-08-29T07:56:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-21T13:55:02Z"
    lastUpdateTime: "2025-10-31T09:26:53Z"
    message: ReplicaSet "agents-mmjc-test-6667574f44" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 102
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
