apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"code-analysis-api","app.kubernetes.io/version":"dev","component":"server","environment":"dev","managed-by":"kustomize"},"name":"code-analysis-api","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"code-analysis-api","app.kubernetes.io/version":"dev","environment":"dev","managed-by":"kustomize"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"9090","prometheus.io/scrape":"true"},"labels":{"app":"code-analysis-api","app.kubernetes.io/version":"dev","component":"server","environment":"dev","managed-by":"kustomize"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["code-analysis-api"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"containers":[{"env":[{"name":"S3_ENDPOINT_URL","valueFrom":{"configMapKeyRef":{"key":"S3_ENDPOINT_URL","name":"code-analysis-config"}}},{"name":"S3_REGION","valueFrom":{"configMapKeyRef":{"key":"S3_REGION","name":"code-analysis-config"}}},{"name":"S3_BUCKET","valueFrom":{"configMapKeyRef":{"key":"S3_BUCKET","name":"code-analysis-config"}}},{"name":"S3_BUCKET_INPUT","valueFrom":{"configMapKeyRef":{"key":"S3_BUCKET_INPUT","name":"code-analysis-config"}}},{"name":"S3_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"S3_ACCESS_KEY","name":"s3-access-key-tools"}}},{"name":"S3_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"S3_SECRET_KEY","name":"s3-secret-key-tools"}}},{"name":"SERVER_PORT","valueFrom":{"configMapKeyRef":{"key":"SERVER_PORT","name":"code-analysis-config"}}},{"name":"METRICS_PORT","valueFrom":{"configMapKeyRef":{"key":"METRICS_PORT","name":"code-analysis-config"}}},{"name":"LOG_LEVEL","valueFrom":{"configMapKeyRef":{"key":"LOG_LEVEL","name":"code-analysis-config"}}},{"name":"LOG_FORMAT","valueFrom":{"configMapKeyRef":{"key":"LOG_FORMAT","name":"code-analysis-config"}}},{"name":"RUST_LOG","valueFrom":{"configMapKeyRef":{"key":"RUST_LOG","name":"code-analysis-config"}}},{"name":"RUST_BACKTRACE","valueFrom":{"configMapKeyRef":{"key":"RUST_BACKTRACE","name":"code-analysis-config"}}},{"name":"CODEQL_DATABASE_PATH","valueFrom":{"configMapKeyRef":{"key":"CODEQL_DATABASE_PATH","name":"code-analysis-config"}}},{"name":"CODEQL_ENABLE_REUSE","valueFrom":{"configMapKeyRef":{"key":"CODEQL_ENABLE_REUSE","name":"code-analysis-config"}}},{"name":"AUTO_DETECT_LANGUAGES","valueFrom":{"configMapKeyRef":{"key":"AUTO_DETECT_LANGUAGES","name":"code-analysis-config"}}},{"name":"ANALYSIS_PARALLEL_WORKERS","valueFrom":{"configMapKeyRef":{"key":"ANALYSIS_PARALLEL_WORKERS","name":"code-analysis-config"}}},{"name":"ANALYSIS_TIMEOUT","valueFrom":{"configMapKeyRef":{"key":"ANALYSIS_TIMEOUT","name":"code-analysis-config"}}},{"name":"S3_MAX_CONNECTIONS","valueFrom":{"configMapKeyRef":{"key":"S3_MAX_CONNECTIONS","name":"code-analysis-config"}}},{"name":"S3_UPLOAD_WORKERS","valueFrom":{"configMapKeyRef":{"key":"S3_UPLOAD_WORKERS","name":"code-analysis-config"}}},{"name":"ENABLE_BINDING_ANALYSIS","valueFrom":{"configMapKeyRef":{"key":"ENABLE_BINDING_ANALYSIS","name":"code-analysis-config"}}},{"name":"ENABLE_DATABASE_REUSE","valueFrom":{"configMapKeyRef":{"key":"ENABLE_DATABASE_REUSE","name":"code-analysis-config"}}}],"image":"icr.io/mjc-cr/code-analysis-api:dev-latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":30,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":10},"name":"code-analysis-api","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"},{"containerPort":9090,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"cpu":"1000m","ephemeral-storage":"5Gi","memory":"2Gi"},"requests":{"cpu":"100m","ephemeral-storage":"500Mi","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"startupProbe":{"failureThreshold":12,"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":10,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":5},"volumeMounts":[{"mountPath":"/tmp","name":"tmp-volume"},{"mountPath":"/cache","name":"analysis-cache"},{"mountPath":"/workspace","name":"codeql-workspace"}]}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}],"securityContext":{"fsGroup":1001,"runAsGroup":1001,"runAsNonRoot":true,"runAsUser":1001},"serviceAccountName":"code-analysis-api","volumes":[{"emptyDir":{"sizeLimit":"5Gi"},"name":"tmp-volume"},{"emptyDir":{"sizeLimit":"10Gi"},"name":"analysis-cache"},{"emptyDir":{"sizeLimit":"20Gi"},"name":"codeql-workspace"}]}}}}
  creationTimestamp: "2025-10-30T05:15:02Z"
  generation: 2
  labels:
    app: code-analysis-api
    app.kubernetes.io/version: dev
    component: server
    environment: dev
    managed-by: kustomize
  name: code-analysis-api
  namespace: mmjc-dev
  resourceVersion: "54774967"
  uid: cbcfff27-8f2c-4f45-9689-cca34675722c
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: code-analysis-api
      app.kubernetes.io/version: dev
      environment: dev
      managed-by: kustomize
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: code-analysis-api
        app.kubernetes.io/version: dev
        component: server
        environment: dev
        managed-by: kustomize
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - code-analysis-api
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: S3_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              key: S3_ENDPOINT_URL
              name: code-analysis-config
        - name: S3_REGION
          valueFrom:
            configMapKeyRef:
              key: S3_REGION
              name: code-analysis-config
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              key: S3_BUCKET
              name: code-analysis-config
        - name: S3_BUCKET_INPUT
          valueFrom:
            configMapKeyRef:
              key: S3_BUCKET_INPUT
              name: code-analysis-config
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY
              name: s3-access-key-tools
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_KEY
              name: s3-secret-key-tools
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: SERVER_PORT
              name: code-analysis-config
        - name: METRICS_PORT
          valueFrom:
            configMapKeyRef:
              key: METRICS_PORT
              name: code-analysis-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: code-analysis-config
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              key: LOG_FORMAT
              name: code-analysis-config
        - name: RUST_LOG
          valueFrom:
            configMapKeyRef:
              key: RUST_LOG
              name: code-analysis-config
        - name: RUST_BACKTRACE
          valueFrom:
            configMapKeyRef:
              key: RUST_BACKTRACE
              name: code-analysis-config
        - name: CODEQL_DATABASE_PATH
          valueFrom:
            configMapKeyRef:
              key: CODEQL_DATABASE_PATH
              name: code-analysis-config
        - name: CODEQL_ENABLE_REUSE
          valueFrom:
            configMapKeyRef:
              key: CODEQL_ENABLE_REUSE
              name: code-analysis-config
        - name: AUTO_DETECT_LANGUAGES
          valueFrom:
            configMapKeyRef:
              key: AUTO_DETECT_LANGUAGES
              name: code-analysis-config
        - name: ANALYSIS_PARALLEL_WORKERS
          valueFrom:
            configMapKeyRef:
              key: ANALYSIS_PARALLEL_WORKERS
              name: code-analysis-config
        - name: ANALYSIS_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: ANALYSIS_TIMEOUT
              name: code-analysis-config
        - name: S3_MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              key: S3_MAX_CONNECTIONS
              name: code-analysis-config
        - name: S3_UPLOAD_WORKERS
          valueFrom:
            configMapKeyRef:
              key: S3_UPLOAD_WORKERS
              name: code-analysis-config
        - name: ENABLE_BINDING_ANALYSIS
          valueFrom:
            configMapKeyRef:
              key: ENABLE_BINDING_ANALYSIS
              name: code-analysis-config
        - name: ENABLE_DATABASE_REUSE
          valueFrom:
            configMapKeyRef:
              key: ENABLE_DATABASE_REUSE
              name: code-analysis-config
        image: icr.io/mjc-cr/code-analysis-api:dev-latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: code-analysis-api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 5Gi
            memory: 2Gi
          requests:
            cpu: 100m
            ephemeral-storage: 500Mi
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        startupProbe:
          failureThreshold: 12
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /cache
          name: analysis-cache
        - mountPath: /workspace
          name: codeql-workspace
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccount: code-analysis-api
      serviceAccountName: code-analysis-api
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 5Gi
        name: tmp-volume
      - emptyDir:
          sizeLimit: 10Gi
        name: analysis-cache
      - emptyDir:
          sizeLimit: 20Gi
        name: codeql-workspace
status:
  conditions:
  - lastTransitionTime: "2025-10-30T05:15:02Z"
    lastUpdateTime: "2025-10-30T05:15:02Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-10-30T05:25:19Z"
    lastUpdateTime: "2025-10-30T05:25:19Z"
    message: ReplicaSet "code-analysis-api-64f4d99bc6" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
