apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "116"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"frontend-mmjc-dev","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"frontend-mmjc"}},"strategy":{"rollingUpdate":{"maxSurge":0,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"labels":{"app":"frontend-mmjc"}},"spec":{"containers":[{"env":[{"name":"PROCESS_ORCHESTRATOR_URL","value":"http://po-mmjc-dev.mmjc-dev.svc.cluster.local:80"},{"name":"CAST_BASE_URL","value":"http://backend.mcp-agent-experiment.svc.cluster.local:8000"},{"name":"API_BASE_ROUTE","value":"/api"},{"name":"NODE_ENV","value":"production"},{"name":"PORT","value":"8080"},{"name":"OIDC_JWKS_URI","value":"https://preprod.login.w3.ibm.com/oidc/endpoint/default/jwks"},{"name":"OIDC_AUTHORITY","value":"https://preprod.login.w3.ibm.com/v1.0/endpoint/default/authorize"},{"name":"OIDC_REDIRECT_URI","value":"https://mmjc-dev.mjc-cluster-c97c2ce0266e6f32de317d52e2a84f46-0001.us-south.containers.appdomain.cloud/auth"},{"name":"OIDC_ISSUER","value":"https://preprod.login.w3.ibm.com/oidc/endpoint/default"},{"name":"OIDC_RESPONSE_TYPE","value":"id_token token"},{"name":"OIDC_SCOPE","value":"openid profile email"},{"name":"OIDC_CLIENT_ID","value":"YTIyOTVkMDktNzI0Zi00"},{"name":"OIDC_IBMID_AUTHORITY","value":"https://prepiam.ice.ibmcloud.com/v1.0/endpoint/default/authorize"},{"name":"OIDC_IBMID_JWKS_URI","value":"https://prepiam.ice.ibmcloud.com/v1.0/endpoint/default/jwks"},{"name":"OIDC_IBMID_ISSUER","value":"https://prepiam.ice.ibmcloud.com/oidc/endpoint/default"},{"name":"OIDC_IBMID_CLIENT_ID","value":"NjdmOTA3MzUtZTk2ZC00"},{"name":"OIDC_IBMID_REDIRECT_URI","value":"https://mmjc-dev.mjc-cluster-c97c2ce0266e6f32de317d52e2a84f46-0001.us-south.containers.appdomain.cloud/auth"},{"name":"OIDC_IBMID_RESPONSE_TYPE","value":"id_token token"},{"name":"OIDC_IBMID_SCOPE","value":"openid profile email"},{"name":"JWT_EXPIRES_IN","value":"1h"},{"name":"JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"JWT_SECRET","name":"jwt-secret-bff"}}},{"name":"IBMID_JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"IBMID_JWT_SECRET","name":"ibmid-jwt-secret-bff"}}},{"name":"BASIC_AUTH_PASS","valueFrom":{"secretKeyRef":{"key":"BASIC_AUTH_PASS","name":"basic-auth-pass-bff"}}}],"image":"icr.io/mjc-cr/mmjc-frontend:0.0.1","imagePullPolicy":"Always","name":"frontend","ports":[{"containerPort":8080,"name":"frontend"}],"resources":{"limits":{"cpu":0.25,"memory":"1Gi"},"requests":{"cpu":0.125,"memory":"1Gi"}}}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}]}}}}
  creationTimestamp: "2025-05-26T10:19:53Z"
  generation: 125
  name: frontend-mmjc-dev
  namespace: mmjc-dev
  resourceVersion: "55237421"
  uid: 987b61f2-7eff-4ba5-b991-44a0bd1db449
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend-mmjc
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-31T16:12:04+02:00"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: frontend-mmjc
    spec:
      containers:
      - env:
        - name: PROCESS_ORCHESTRATOR_URL
          value: http://po-mmjc-dev.mmjc-dev.svc.cluster.local:80
        - name: CAST_BASE_URL
          value: http://backend.mcp-agent-experiment.svc.cluster.local:8000
        - name: API_BASE_ROUTE
          value: /api
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "8080"
        - name: OIDC_JWKS_URI
          value: https://preprod.login.w3.ibm.com/oidc/endpoint/default/jwks
        - name: OIDC_AUTHORITY
          value: https://preprod.login.w3.ibm.com/v1.0/endpoint/default/authorize
        - name: OIDC_REDIRECT_URI
          value: https://mmjc-dev.mjc-cluster-c97c2ce0266e6f32de317d52e2a84f46-0001.us-south.containers.appdomain.cloud/auth
        - name: OIDC_ISSUER
          value: https://preprod.login.w3.ibm.com/oidc/endpoint/default
        - name: OIDC_RESPONSE_TYPE
          value: id_token token
        - name: OIDC_SCOPE
          value: openid profile email
        - name: OIDC_CLIENT_ID
          value: YTIyOTVkMDktNzI0Zi00
        - name: OIDC_IBMID_AUTHORITY
          value: https://prepiam.ice.ibmcloud.com/v1.0/endpoint/default/authorize
        - name: OIDC_IBMID_JWKS_URI
          value: https://prepiam.ice.ibmcloud.com/v1.0/endpoint/default/jwks
        - name: OIDC_IBMID_ISSUER
          value: https://prepiam.ice.ibmcloud.com/oidc/endpoint/default
        - name: OIDC_IBMID_CLIENT_ID
          value: NjdmOTA3MzUtZTk2ZC00
        - name: OIDC_IBMID_REDIRECT_URI
          value: https://mmjc-dev.mjc-cluster-c97c2ce0266e6f32de317d52e2a84f46-0001.us-south.containers.appdomain.cloud/auth
        - name: OIDC_IBMID_RESPONSE_TYPE
          value: id_token token
        - name: OIDC_IBMID_SCOPE
          value: openid profile email
        - name: JWT_EXPIRES_IN
          value: 1h
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: jwt-secret-bff
        - name: IBMID_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: IBMID_JWT_SECRET
              name: ibmid-jwt-secret-bff
        - name: BASIC_AUTH_PASS
          valueFrom:
            secretKeyRef:
              key: BASIC_AUTH_PASS
              name: basic-auth-pass-bff
        image: icr.io/mjc-cr/mmjc-frontend:0.0.1
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 8080
          name: frontend
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-26T10:19:53Z"
    lastUpdateTime: "2025-05-26T10:19:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-04T20:44:24Z"
    lastUpdateTime: "2025-10-31T14:12:12Z"
    message: ReplicaSet "frontend-mmjc-dev-56c9699f5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 125
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
