apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "27"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mermaid-validator-api","environment":"dev","managed-by":"kustomize","version":"1.0.0"},"name":"mermaid-validator-api","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mermaid-validator-api","environment":"dev","managed-by":"kustomize"}},"template":{"metadata":{"labels":{"app":"mermaid-validator-api","environment":"dev","managed-by":"kustomize","version":"1.0.1"}},"spec":{"containers":[{"env":[{"name":"NODE_ENV","value":"development"},{"name":"LOG_LEVEL","value":"debug"},{"name":"PORT","value":"8000"}],"image":"icr.io/mjc-cr/mjc-mermaid-validator:1.0.0-amd64","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/v1/health","port":"http"},"initialDelaySeconds":30,"periodSeconds":30,"timeoutSeconds":10},"name":"mermaid-validator-api","ports":[{"containerPort":8000,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/v1/health","port":"http"},"initialDelaySeconds":10,"periodSeconds":5,"timeoutSeconds":5},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"volumeMounts":[{"mountPath":"/app/tmp","name":"tmp-volume"},{"mountPath":"/app/logs","name":"logs-volume"}]}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}],"restartPolicy":"Always","securityContext":{"fsGroup":1001,"runAsGroup":1001,"runAsNonRoot":true,"runAsUser":1001},"terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"tmp-volume"},{"emptyDir":{},"name":"logs-volume"}]}}}}
  creationTimestamp: "2025-09-11T07:07:41Z"
  generation: 57
  labels:
    app: mermaid-validator-api
    environment: dev
    managed-by: kustomize
    version: 1.0.0
  name: mermaid-validator-api
  namespace: mmjc-dev
  resourceVersion: "51369416"
  uid: e9bed35e-d15e-4965-950a-84f5c9ab8751
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mermaid-validator-api
      environment: dev
      managed-by: kustomize
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-09-19T14:08:29-03:00"
      creationTimestamp: null
      labels:
        app: mermaid-validator-api
        environment: dev
        managed-by: kustomize
        version: 1.0.1
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        - name: LOG_LEVEL
          value: debug
        - name: PORT
          value: "8000"
        image: icr.io/mjc-cr/mjc-mermaid-validator:1.0.17-llm-ready-amd64
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: mermaid-validator-api
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/tmp
          name: tmp-volume
        - mountPath: /app/logs
          name: logs-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp-volume
      - emptyDir: {}
        name: logs-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-09-19T13:54:06Z"
    lastUpdateTime: "2025-09-24T20:57:33Z"
    message: ReplicaSet "mermaid-validator-api-84d5679f4c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-20T12:23:22Z"
    lastUpdateTime: "2025-10-20T12:23:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 57
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
