apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: milvus-mmjc-dev
    meta.helm.sh/release-namespace: mmjc-dev
  creationTimestamp: "2025-07-31T07:18:53Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: milvus
    app.kubernetes.io/version: 2.5.15
    component: datanode
    helm.sh/chart: milvus-4.2.57
  name: milvus-mmjc-dev-datanode
  namespace: mmjc-dev
  resourceVersion: "22637854"
  uid: 462b9fc8-970f-4a71-82e9-c8db22ac7683
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: milvus-mmjc-dev
      app.kubernetes.io/name: milvus
      component: datanode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 7fd9be72867e2683fa94f9eb59994829f1bc1ba881a870cda0993c4c4a6ecd11
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: milvus-mmjc-dev
        app.kubernetes.io/name: milvus
        component: datanode
    spec:
      containers:
      - args:
        - milvus
        - run
        - datanode
        image: milvusdb/milvus:v2.5.15
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: metrics
          timeoutSeconds: 5
        name: datanode
        ports:
        - containerPort: 21124
          name: datanode
          protocol: TCP
        - containerPort: 9091
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /milvus/configs/default.yaml
          name: milvus-config
          readOnly: true
          subPath: default.yaml
        - mountPath: /milvus/configs/user.yaml
          name: milvus-config
          readOnly: true
          subPath: user.yaml
        - mountPath: /milvus/tools
          name: tools
      dnsPolicy: ClusterFirst
      nodeSelector:
        ibm-cloud.kubernetes.io/worker-pool-name: milvus-pool
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: reserved
        operator: Equal
        value: milvus
      volumes:
      - configMap:
          defaultMode: 420
          name: milvus-mmjc-dev
        name: milvus-config
      - emptyDir: {}
        name: tools
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-07-31T07:21:44Z"
    lastUpdateTime: "2025-07-31T07:21:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-31T07:18:53Z"
    lastUpdateTime: "2025-07-31T07:21:44Z"
    message: ReplicaSet "milvus-mmjc-dev-datanode-7865b55c9c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
