apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"attu"},"name":"my-attu","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"attu"}},"template":{"metadata":{"labels":{"app":"attu"}},"spec":{"containers":[{"env":[{"name":"MILVUS_URL","value":"milvus-mmjc-dev.mmjc-dev.svc.cluster.local:19530"}],"image":"zilliz/attu:v2.5.6","imagePullPolicy":"IfNotPresent","name":"attu","ports":[{"containerPort":3000,"name":"attu","protocol":"TCP"}]}],"nodeSelector":{"ibm-cloud.kubernetes.io/worker-pool-name":"milvus-pool"},"tolerations":[{"effect":"NoSchedule","key":"reserved","operator":"Equal","value":"milvus"}]}}}}
  creationTimestamp: "2025-07-31T09:22:39Z"
  generation: 2
  labels:
    app: attu
  name: my-attu
  namespace: mmjc-dev
  resourceVersion: "22667684"
  uid: f419acfd-3ba9-41af-8403-448b688199b4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: attu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: attu
    spec:
      containers:
      - env:
        - name: MILVUS_URL
          value: milvus-mmjc-dev.mmjc-dev.svc.cluster.local:19530
        image: zilliz/attu:v2.5.6
        imagePullPolicy: IfNotPresent
        name: attu
        ports:
        - containerPort: 3000
          name: attu
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        ibm-cloud.kubernetes.io/worker-pool-name: milvus-pool
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: reserved
        operator: Equal
        value: milvus
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-31T09:24:09Z"
    lastUpdateTime: "2025-07-31T09:24:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-31T09:22:39Z"
    lastUpdateTime: "2025-07-31T09:24:09Z"
    message: ReplicaSet "my-attu-779895b486" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
