apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "118"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"po-mmjc-dev","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"po-mmjc"}},"strategy":{"rollingUpdate":{"maxSurge":0,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"labels":{"app":"po-mmjc"}},"spec":{"containers":[{"env":[{"name":"DB_URL","value":"38cbe469-657f-4988-b1ea-cfb0d2e5a24a.btdl8mld0r95fevivv30.private.databases.appdomain.cloud"},{"name":"DB_PORT","value":"32396"},{"name":"DB_USER","value":"ibm_cloud_851f5bb2_aedf_4280_bb1e_863ad3ac3503"},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"DB_PASSWORD","name":"db-password-po"}}},{"name":"DB_NAME","value":"mmjc"},{"name":"AGENTS_SERVER_URL","value":"http://agents-mmjc-dev.mmjc-dev.svc.cluster.local:80/agent_langgraph/invoke"},{"name":"API_KEY_NAME","value":"API-Key"},{"name":"API_KEY","valueFrom":{"secretKeyRef":{"key":"API_KEY","name":"api-key-po"}}},{"name":"COS_ENDPOINT_URL","value":"https://s3.us-south.cloud-object-storage.appdomain.cloud"},{"name":"COS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"S3_ACCESS_KEY","name":"s3-access-key-tools"}}},{"name":"COS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"S3_SECRET_KEY","name":"s3-secret-key-tools"}}},{"name":"LOG_LEVEL","value":"INFO"},{"name":"MAX_THREADS","value":"10"},{"name":"COS_MAX_KEYS","value":"1000"},{"name":"API_TIMEOUT_SEC","value":"240"},{"name":"DEFAULT_ROLE","value":"BLOCKED"},{"name":"AIRFLOW_TOKEN_URL","value":"http://airflow-dev-api-server.airflow-dev.svc.cluster.local:8080/auth/token"},{"name":"AIRFLOW_URL","value":"http://airflow-dev-api-server.airflow-dev.svc.cluster.local:8080/api/v2/"},{"name":"AIRFLOW_USERNAME","valueFrom":{"secretKeyRef":{"key":"AIRFLOW_USERNAME","name":"airflow-secret-dev"}}},{"name":"AIRFLOW_PASSWORD","valueFrom":{"secretKeyRef":{"key":"AIRFLOW_PASSWORD","name":"airflow-secret-dev"}}},{"name":"CAST_BACKEND_URL","value":"http://backend.mcp-agent-experiment.svc.cluster.local:8000"}],"image":"icr.io/mjc-cr/mmjc-po:0.0.1","imagePullPolicy":"Always","name":"po","ports":[{"containerPort":8080,"name":"po-mmjc"}],"resources":{"limits":{"cpu":0.25,"memory":"1Gi"},"requests":{"cpu":0.125,"memory":"1Gi"}}}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}]}}}}
  creationTimestamp: "2025-05-23T06:54:31Z"
  generation: 134
  name: po-mmjc-dev
  namespace: mmjc-dev
  resourceVersion: "55179449"
  uid: e34efdc7-250b-4761-ae4a-59ec47a0a373
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: po-mmjc
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-31T10:04:50Z"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: po-mmjc
    spec:
      containers:
      - env:
        - name: DB_URL
          value: 38cbe469-657f-4988-b1ea-cfb0d2e5a24a.btdl8mld0r95fevivv30.private.databases.appdomain.cloud
        - name: DB_PORT
          value: "32396"
        - name: DB_USER
          value: ibm_cloud_851f5bb2_aedf_4280_bb1e_863ad3ac3503
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: db-password-po
        - name: DB_NAME
          value: mmjc
        - name: AGENTS_SERVER_URL
          value: http://agents-mmjc-dev.mmjc-dev.svc.cluster.local:80/agent_langgraph/invoke
        - name: API_KEY_NAME
          value: API-Key
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: API_KEY
              name: api-key-po
        - name: COS_ENDPOINT_URL
          value: https://s3.us-south.cloud-object-storage.appdomain.cloud
        - name: COS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY
              name: s3-access-key-tools
        - name: COS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_KEY
              name: s3-secret-key-tools
        - name: LOG_LEVEL
          value: INFO
        - name: MAX_THREADS
          value: "10"
        - name: COS_MAX_KEYS
          value: "1000"
        - name: API_TIMEOUT_SEC
          value: "240"
        - name: DEFAULT_ROLE
          value: BLOCKED
        - name: AIRFLOW_TOKEN_URL
          value: http://airflow-dev-api-server.airflow-dev.svc.cluster.local:8080/auth/token
        - name: AIRFLOW_URL
          value: http://airflow-dev-api-server.airflow-dev.svc.cluster.local:8080/api/v2/
        - name: AIRFLOW_USERNAME
          valueFrom:
            secretKeyRef:
              key: AIRFLOW_USERNAME
              name: airflow-secret-dev
        - name: AIRFLOW_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AIRFLOW_PASSWORD
              name: airflow-secret-dev
        - name: CAST_BACKEND_URL
          value: http://backend.mcp-agent-experiment.svc.cluster.local:8000
        image: icr.io/mjc-cr/mmjc-po:0.0.1
        imagePullPolicy: Always
        name: po
        ports:
        - containerPort: 8080
          name: po-mmjc
          protocol: TCP
        - containerPort: 8000
          name: po
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-23T06:54:31Z"
    lastUpdateTime: "2025-05-23T06:54:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-23T07:35:53Z"
    lastUpdateTime: "2025-10-31T10:04:54Z"
    message: ReplicaSet "po-mmjc-dev-85fc79b96d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 134
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
