apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"postgres-langfuse","component":"database"},"name":"postgres-langfuse","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"postgres-langfuse"}},"template":{"metadata":{"labels":{"app":"postgres-langfuse","component":"database"}},"spec":{"containers":[{"env":[{"name":"POSTGRES_USER","value":"langfuse"},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"postgres-langfuse-credentials"}}},{"name":"POSTGRES_DB","value":"langfuse"},{"name":"PGDATA","value":"/var/lib/postgresql/data/pgdata"}],"image":"postgres:15-alpine","imagePullPolicy":"IfNotPresent","name":"postgres","ports":[{"containerPort":5432,"name":"postgres","protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/var/lib/postgresql/data","name":"postgres-data"}]}],"volumes":[{"name":"postgres-data","persistentVolumeClaim":{"claimName":"postgres-langfuse-pvc"}}]}}}}
  creationTimestamp: "2025-10-22T16:31:50Z"
  generation: 1
  labels:
    app: postgres-langfuse
    component: database
  name: postgres-langfuse
  namespace: mmjc-dev
  resourceVersion: "52172894"
  uid: b0dd7f4e-feb0-4356-9d8c-2e92c8d995ef
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres-langfuse
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-langfuse
        component: database
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: langfuse
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-langfuse-credentials
        - name: POSTGRES_DB
          value: langfuse
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-langfuse-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-22T16:32:24Z"
    lastUpdateTime: "2025-10-22T16:32:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-22T16:31:50Z"
    lastUpdateTime: "2025-10-22T16:32:24Z"
    message: ReplicaSet "postgres-langfuse-7475bf4656" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
