apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"prefect-worker-arc","component":"worker","version":"v1.5.5"},"name":"prefect-worker-arc","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"prefect-worker-arc"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"labels":{"app":"prefect-worker-arc","component":"worker","version":"v1.5.5"}},"spec":{"containers":[{"command":["prefect","worker","start","--pool","arc-extraction-pool","--type","process"],"env":[{"name":"PREFECT_API_URL","value":"http://prefect-server.mmjc-dev.svc.cluster.local:4200/api"},{"name":"PREFECT_LOGGING_LEVEL","value":"INFO"},{"name":"AWS_ENDPOINT_URL","value":"https://s3.direct.us-south.cloud-object-storage.appdomain.cloud"},{"name":"AWS_DEFAULT_REGION","value":"us-east"},{"name":"AWS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"S3_ACCESS_KEY","name":"s3-access-key-tools"}}},{"name":"AWS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"S3_SECRET_KEY","name":"s3-secret-key-tools"}}},{"name":"S3_BUCKET","value":"mmjc-dev"},{"name":"VALKEY_HOST","value":"valkey-single.mmjc-dev.svc.cluster.local"},{"name":"VALKEY_PORT","value":"6379"},{"name":"VALKEY_DB","value":"0"},{"name":"VALKEY_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"valkey-credentials","optional":true}}},{"name":"LANGFUSE_HOST","value":"http://langfuse.mmjc-dev.svc.cluster.local:3000"},{"name":"LANGFUSE_PUBLIC_KEY","valueFrom":{"secretKeyRef":{"key":"public_key","name":"langfuse-credentials","optional":true}}},{"name":"LANGFUSE_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"secret_key","name":"langfuse-credentials","optional":true}}}],"envFrom":[{"configMapRef":{"name":"arc-extractor-config"}},{"secretRef":{"name":"arc-extractor-llm-credentials","optional":false}}],"image":"icr.io/mjc-cr/understanding-agent-arc:1.5.5","imagePullPolicy":"Always","name":"prefect-worker","resources":{"limits":{"cpu":"2000m","memory":"4Gi"},"requests":{"cpu":"1000m","memory":"2Gi"}},"volumeMounts":[{"mountPath":"/app/logs","name":"worker-logs"}]}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}],"volumes":[{"emptyDir":{"sizeLimit":"2Gi"},"name":"worker-logs"}]}}}}
  creationTimestamp: "2025-10-22T12:22:17Z"
  generation: 3
  labels:
    app: prefect-worker-arc
    component: worker
    version: v1.5.5
  name: prefect-worker-arc
  namespace: mmjc-dev
  resourceVersion: "52862736"
  uid: 908da8db-22f9-4229-aa52-c0d2fa27dc71
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prefect-worker-arc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-22T09:23:58-03:00"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: prefect-worker-arc
        component: worker
        version: v1.5.5
    spec:
      containers:
      - command:
        - prefect
        - worker
        - start
        - --pool
        - arc-extraction-pool
        - --type
        - process
        env:
        - name: PREFECT_API_URL
          value: http://prefect-server.mmjc-dev.svc.cluster.local:4200/api
        - name: PREFECT_LOGGING_LEVEL
          value: INFO
        - name: AWS_ENDPOINT_URL
          value: https://s3.direct.us-south.cloud-object-storage.appdomain.cloud
        - name: AWS_DEFAULT_REGION
          value: us-east
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY
              name: s3-access-key-tools
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_KEY
              name: s3-secret-key-tools
        - name: S3_BUCKET
          value: mmjc-dev
        - name: VALKEY_HOST
          value: valkey-single.mmjc-dev.svc.cluster.local
        - name: VALKEY_PORT
          value: "6379"
        - name: VALKEY_DB
          value: "0"
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: valkey-credentials
              optional: true
        - name: LANGFUSE_HOST
          value: http://langfuse.mmjc-dev.svc.cluster.local:3000
        - name: LANGFUSE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: public_key
              name: langfuse-credentials
              optional: true
        - name: LANGFUSE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret_key
              name: langfuse-credentials
              optional: true
        envFrom:
        - configMapRef:
            name: arc-extractor-config
        - secretRef:
            name: arc-extractor-llm-credentials
            optional: false
        image: icr.io/mjc-cr/understanding-agent-arc:1.5.5
        imagePullPolicy: Always
        name: prefect-worker
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/logs
          name: worker-logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 2Gi
        name: worker-logs
status:
  conditions:
  - lastTransitionTime: "2025-10-24T13:27:40Z"
    lastUpdateTime: "2025-10-24T13:27:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-24T13:27:40Z"
    lastUpdateTime: "2025-10-24T13:27:40Z"
    message: ReplicaSet "prefect-worker-arc-66df948b6f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
