apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"prefect-server","component":"orchestration"},"name":"prefect-server","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"prefect-server"}},"template":{"metadata":{"labels":{"app":"prefect-server","component":"orchestration"}},"spec":{"containers":[{"command":["prefect","server","start","--host","0.0.0.0"],"env":[{"name":"PREFECT_SERVER_API_HOST","value":"0.0.0.0"},{"name":"PREFECT_SERVER_API_PORT","value":"4200"},{"name":"PREFECT_API_DATABASE_CONNECTION_URL","value":"postgresql+asyncpg://prefect:prefect@postgres-prefect.mmjc-dev.svc.cluster.local:5432/prefect"},{"name":"PREFECT_LOGGING_LEVEL","value":"INFO"}],"image":"prefecthq/prefect:3-python3.11","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/api/health","port":4200},"initialDelaySeconds":30,"periodSeconds":30},"name":"prefect-server","ports":[{"containerPort":4200,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/api/health","port":4200},"initialDelaySeconds":10,"periodSeconds":10},"resources":{"limits":{"cpu":"1000m","memory":"1Gi"},"requests":{"cpu":"500m","memory":"512Mi"}}}]}}}}
  creationTimestamp: "2025-10-22T12:22:14Z"
  generation: 2
  labels:
    app: prefect-server
    component: orchestration
  name: prefect-server
  namespace: mmjc-dev
  resourceVersion: "52109075"
  uid: 6bc51063-4322-41a0-a312-b526fdf54b0c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prefect-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-22T09:23:58-03:00"
      creationTimestamp: null
      labels:
        app: prefect-server
        component: orchestration
    spec:
      containers:
      - command:
        - prefect
        - server
        - start
        - --host
        - 0.0.0.0
        env:
        - name: PREFECT_SERVER_API_HOST
          value: 0.0.0.0
        - name: PREFECT_SERVER_API_PORT
          value: "4200"
        - name: PREFECT_API_DATABASE_CONNECTION_URL
          value: postgresql+asyncpg://prefect:prefect@postgres-prefect.mmjc-dev.svc.cluster.local:5432/prefect
        - name: PREFECT_LOGGING_LEVEL
          value: INFO
        image: prefecthq/prefect:3-python3.11
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 4200
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: prefect-server
        ports:
        - containerPort: 4200
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 4200
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-22T12:24:19Z"
    lastUpdateTime: "2025-10-22T12:24:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-22T12:22:14Z"
    lastUpdateTime: "2025-10-22T12:24:19Z"
    message: ReplicaSet "prefect-server-7b8f9499b4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
