apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "85"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"understanding-agent-arc-worker","component":"worker","version":"v1.6.53"},"name":"understanding-agent-arc-worker","namespace":"mmjc-dev"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"understanding-agent-arc-worker","component":"worker"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"labels":{"app":"understanding-agent-arc-worker","component":"worker","version":"v1.6.53"}},"spec":{"containers":[{"command":["python","-m","arc_extractor.worker.worker"],"env":[{"name":"AWS_ENDPOINT_URL","value":"https://s3.us-south.cloud-object-storage.appdomain.cloud"},{"name":"AWS_DEFAULT_REGION","value":"us-east"},{"name":"AWS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"S3_ACCESS_KEY","name":"s3-access-key-tools"}}},{"name":"AWS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"S3_SECRET_KEY","name":"s3-secret-key-tools"}}},{"name":"S3_BUCKET","value":"bucket-v1hdvzfyotonx3x"},{"name":"S3_OUTPUT_PREFIX","value":"data-job-mcp-test-run/ai_results"},{"name":"VALKEY_HOST","value":"valkey-service.mmjc-dev.svc.cluster.local"},{"name":"VALKEY_PORT","value":"6379"},{"name":"VALKEY_DB","value":"0"},{"name":"VALKEY_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"valkey-credentials","optional":true}}},{"name":"WORKER_ID","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"WORKER_HEARTBEAT_INTERVAL","value":"30"},{"name":"WORKER_POLL_INTERVAL","value":"5"},{"name":"WORKER_TASK_TIMEOUT","value":"3600"},{"name":"LOG_LEVEL","value":"INFO"},{"name":"CONSOLE_LOG","value":"true"}],"envFrom":[{"configMapRef":{"name":"arc-extractor-env"}},{"secretRef":{"name":"arc-extractor-llm-credentials","optional":false}}],"image":"icr.io/mjc-cr/understanding-agent-arc:1.6.53","imagePullPolicy":"Always","lifecycle":{"preStop":{"exec":{"command":["/bin/sh","-c","sleep 30"]}}},"name":"worker","resources":{"limits":{"cpu":"2000m","memory":"4Gi"},"requests":{"cpu":"1000m","memory":"2Gi"}},"volumeMounts":[{"mountPath":"/data/source","name":"source-data"},{"mountPath":"/app/results","name":"results"},{"mountPath":"/app/logs","name":"logs"}]}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}],"restartPolicy":"Always","terminationGracePeriodSeconds":60,"volumes":[{"emptyDir":{"sizeLimit":"50Gi"},"name":"source-data"},{"emptyDir":{"sizeLimit":"20Gi"},"name":"results"},{"emptyDir":{"sizeLimit":"1Gi"},"name":"logs"}]}}}}
  creationTimestamp: "2025-10-20T03:40:27Z"
  generation: 129
  labels:
    app: understanding-agent-arc-worker
    component: worker
    version: v1.6.53
  name: understanding-agent-arc-worker
  namespace: mmjc-dev
  resourceVersion: "55035998"
  uid: 629a7d99-ec64-4ce6-9e93-5bc7f65e79fa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: understanding-agent-arc-worker
      component: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-30T20:47:36-03:00"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: understanding-agent-arc-worker
        component: worker
        version: v1.6.53
    spec:
      containers:
      - command:
        - python
        - -m
        - arc_extractor.worker.worker
        env:
        - name: AWS_ENDPOINT_URL
          value: https://s3.us-south.cloud-object-storage.appdomain.cloud
        - name: AWS_DEFAULT_REGION
          value: us-east
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY
              name: s3-access-key-tools
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_KEY
              name: s3-secret-key-tools
        - name: S3_BUCKET
          value: bucket-v1hdvzfyotonx3x
        - name: S3_OUTPUT_PREFIX
          value: data-job-mcp-test-run/ai_results
        - name: VALKEY_HOST
          value: redis-service-dev.mmjc-dev.svc.cluster.local
        - name: VALKEY_PORT
          value: "6379"
        - name: VALKEY_DB
          value: "0"
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: valkey-credentials
              optional: true
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: WORKER_HEARTBEAT_INTERVAL
          value: "30"
        - name: WORKER_POLL_INTERVAL
          value: "5"
        - name: WORKER_TASK_TIMEOUT
          value: "3600"
        - name: LOG_LEVEL
          value: INFO
        - name: CONSOLE_LOG
          value: "true"
        - name: LANGFUSE_HOST
          value: http://langfuse.mmjc-dev.svc.cluster.local:3000
        - name: LANGFUSE_PUBLIC_KEY
          value: lf_pk_684246d8ae5bdff862826cfbe6077f08
        - name: LANGFUSE_SECRET_KEY
          value: lf_sk_dad9519d6f6ab3d43e895eb0e8bfa3ee81f0b50e3bed8c1c3b127d30af043edf
        envFrom:
        - configMapRef:
            name: arc-extractor-env
        - secretRef:
            name: arc-extractor-llm-credentials
            optional: false
        image: icr.io/mjc-cr/understanding-agent-arc:1.6.62
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 30
        name: worker
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/source
          name: source-data
        - mountPath: /app/results
          name: results
        - mountPath: /app/logs
          name: logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir:
          sizeLimit: 50Gi
        name: source-data
      - emptyDir:
          sizeLimit: 20Gi
        name: results
      - emptyDir:
          sizeLimit: 1Gi
        name: logs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-29T04:18:56Z"
    lastUpdateTime: "2025-10-29T04:18:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-23T16:42:58Z"
    lastUpdateTime: "2025-10-30T23:47:41Z"
    message: ReplicaSet "understanding-agent-arc-worker-6d669f957d" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 129
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
