apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "85"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"understanding-agent-arc","version":"v1.6.53"},"name":"understanding-agent-arc","namespace":"mmjc-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"understanding-agent-arc"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"labels":{"app":"understanding-agent-arc","version":"v1.6.53"}},"spec":{"containers":[{"command":["python","-m","arc_extractor.api.server"],"env":[{"name":"PORT","value":"8080"},{"name":"AWS_ENDPOINT_URL","value":"https://s3.us-south.cloud-object-storage.appdomain.cloud"},{"name":"AWS_DEFAULT_REGION","value":"us-east"},{"name":"AWS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"S3_ACCESS_KEY","name":"s3-access-key-tools"}}},{"name":"AWS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"S3_SECRET_KEY","name":"s3-secret-key-tools"}}},{"name":"S3_BUCKET","value":"mmjc-dev"},{"name":"VALKEY_HOST","value":"valkey-service.mmjc-dev.svc.cluster.local"},{"name":"VALKEY_PORT","value":"6379"},{"name":"VALKEY_DB","value":"0"},{"name":"VALKEY_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"valkey-credentials","optional":true}}}],"envFrom":[{"configMapRef":{"name":"arc-extractor-config"}},{"secretRef":{"name":"arc-extractor-llm-credentials","optional":false}}],"image":"icr.io/mjc-cr/understanding-agent-arc:1.6.53","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":30,"periodSeconds":30},"name":"understanding-agent","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":10,"periodSeconds":10},"resources":{"limits":{"cpu":"1000m","memory":"2Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/data/source","name":"source-data"},{"mountPath":"/app/results","name":"results"},{"mountPath":"/app/logs","name":"logs"}]}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}],"volumes":[{"emptyDir":{"sizeLimit":"50Gi"},"name":"source-data"},{"emptyDir":{"sizeLimit":"20Gi"},"name":"results"},{"emptyDir":{"sizeLimit":"1Gi"},"name":"logs"}]}}}}
  creationTimestamp: "2025-10-14T22:33:00Z"
  generation: 85
  labels:
    app: understanding-agent-arc
    version: v1.6.53
  name: understanding-agent-arc
  namespace: mmjc-dev
  resourceVersion: "54892304"
  uid: 6258eadb-778e-4566-8427-7a66030e7183
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: understanding-agent-arc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-29T18:54:13-03:00"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: understanding-agent-arc
        version: v1.6.53
    spec:
      containers:
      - command:
        - python
        - -m
        - arc_extractor.api.server
        env:
        - name: PORT
          value: "8080"
        - name: AWS_ENDPOINT_URL
          value: https://s3.us-south.cloud-object-storage.appdomain.cloud
        - name: AWS_DEFAULT_REGION
          value: us-east
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY
              name: s3-access-key-tools
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_KEY
              name: s3-secret-key-tools
        - name: S3_BUCKET
          value: mmjc-dev
        - name: VALKEY_HOST
          value: redis-service-dev.mmjc-dev.svc.cluster.local
        - name: VALKEY_PORT
          value: "6379"
        - name: VALKEY_DB
          value: "0"
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: valkey-credentials
              optional: true
        - name: LANGFUSE_HOST
          value: http://langfuse.mmjc-dev.svc.cluster.local:3000
        - name: LANGFUSE_PUBLIC_KEY
          value: lf_pk_684246d8ae5bdff862826cfbe6077f08
        - name: LANGFUSE_SECRET_KEY
          value: lf_sk_dad9519d6f6ab3d43e895eb0e8bfa3ee81f0b50e3bed8c1c3b127d30af043edf
        envFrom:
        - configMapRef:
            name: arc-extractor-config
        - secretRef:
            name: arc-extractor-llm-credentials
            optional: false
        image: icr.io/mjc-cr/understanding-agent-arc:v1.6.60
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: understanding-agent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/source
          name: source-data
        - mountPath: /app/results
          name: results
        - mountPath: /app/logs
          name: logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 50Gi
        name: source-data
      - emptyDir:
          sizeLimit: 20Gi
        name: results
      - emptyDir:
          sizeLimit: 1Gi
        name: logs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-25T19:30:21Z"
    lastUpdateTime: "2025-10-25T19:30:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-19T15:46:52Z"
    lastUpdateTime: "2025-10-30T13:39:49Z"
    message: ReplicaSet "understanding-agent-arc-556476fccf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 85
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
