apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"api-file-zip-s3","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"api-file-zip-s3","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"dev","component":"headless-service","environment":"mmjc-dev"},"name":"api-file-zip-s3-headless","namespace":"mmjc-dev"},"spec":{"clusterIP":"None","ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"api-file-zip-s3","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"api-file-zip-s3","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"dev","environment":"mmjc-dev"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-29T05:32:38Z"
  labels:
    app: api-file-zip-s3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-file-zip-s3
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: dev
    component: headless-service
    environment: mmjc-dev
  name: api-file-zip-s3-headless
  namespace: mmjc-dev
  resourceVersion: "54439553"
  uid: 3993fd7c-e860-4789-b6ac-013c6a9c9158
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: api-file-zip-s3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-file-zip-s3
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: dev
    environment: mmjc-dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
