apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"code-analysis-api","app.kubernetes.io/version":"dev","component":"service","environment":"dev","managed-by":"kustomize"},"name":"code-analysis-api","namespace":"mmjc-dev"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":"http"},{"name":"metrics","port":9090,"protocol":"TCP","targetPort":"metrics"}],"selector":{"app":"code-analysis-api","app.kubernetes.io/version":"dev","environment":"dev","managed-by":"kustomize"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-30T05:15:01Z"
  labels:
    app: code-analysis-api
    app.kubernetes.io/version: dev
    component: service
    environment: dev
    managed-by: kustomize
  name: code-analysis-api
  namespace: mmjc-dev
  resourceVersion: "54772407"
  uid: 93c56c59-d6e9-479b-a263-8ae6ddfd3c22
spec:
  clusterIP: 172.21.101.167
  clusterIPs:
  - 172.21.101.167
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app: code-analysis-api
    app.kubernetes.io/version: dev
    environment: dev
    managed-by: kustomize
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
