apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend-mmjc","namespace":"mmjc-dev"},"spec":{"ports":[{"name":"http-frontend","port":80,"protocol":"TCP","targetPort":"frontend"}],"selector":{"app":"frontend-mmjc"}}}
  creationTimestamp: "2025-07-14T07:26:10Z"
  name: frontend-mmjc
  namespace: mmjc-dev
  resourceVersion: "17758472"
  uid: 9baa3865-b159-4c9f-b65d-309d6c410876
spec:
  clusterIP: 172.21.83.122
  clusterIPs:
  - 172.21.83.122
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-frontend
    port: 80
    protocol: TCP
    targetPort: frontend
  selector:
    app: frontend-mmjc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
