apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"langfuse","component":"observability"},"name":"langfuse","namespace":"mmjc-dev"},"spec":{"ports":[{"name":"http","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"langfuse"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-22T16:20:57Z"
  labels:
    app: langfuse
    component: observability
  name: langfuse
  namespace: mmjc-dev
  resourceVersion: "52169394"
  uid: de1d6762-078e-45bf-92e2-e0e1322669a3
spec:
  clusterIP: 172.21.69.145
  clusterIPs:
  - 172.21.69.145
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: langfuse
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
