apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-dev
    meta.helm.sh/release-namespace: mmjc-dev
  creationTimestamp: "2025-07-31T07:18:53Z"
  labels:
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: milvus
    app.kubernetes.io/version: 2.5.15
    component: mixcoord
    helm.sh/chart: milvus-4.2.57
  name: milvus-mmjc-dev-mixcoord
  namespace: mmjc-dev
  resourceVersion: "22636410"
  uid: 211a5532-7cb1-407e-a4e6-cd0a76d7ff6c
spec:
  clusterIP: 172.21.85.168
  clusterIPs:
  - 172.21.85.168
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/name: milvus
    component: mixcoord
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
