apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-dev
    meta.helm.sh/release-namespace: mmjc-dev
  creationTimestamp: "2025-07-31T07:18:53Z"
  labels:
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-6.3.3
  name: milvus-mmjc-dev-etcd
  namespace: mmjc-dev
  resourceVersion: "22636418"
  uid: 7d66fba7-b0aa-4869-b3ec-90a09f881866
spec:
  clusterIP: 172.21.149.108
  clusterIPs:
  - 172.21.149.108
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: client
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: peer
  selector:
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/name: etcd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
