apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-dev
    meta.helm.sh/release-namespace: mmjc-dev
  creationTimestamp: "2025-07-31T07:18:53Z"
  labels:
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: milvus
    app.kubernetes.io/version: 2.5.15
    component: querynode
    helm.sh/chart: milvus-4.2.57
  name: milvus-mmjc-dev-querynode
  namespace: mmjc-dev
  resourceVersion: "22636388"
  uid: 8092c196-4a66-4800-865c-ed0718da06ed
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/name: milvus
    component: querynode
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
