apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"analyzer","app.kubernetes.io/component":"api","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/part-of":"code-analyzer","environment":"dev","language":"python"},"name":"python-analyzer-service","namespace":"mmjc-dev"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"analyzer","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/part-of":"code-analyzer","environment":"dev","language":"python"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-03T00:10:51Z"
  labels:
    app: analyzer
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: code-analyzer
    environment: dev
    language: python
  name: python-analyzer-service
  namespace: mmjc-dev
  resourceVersion: "44967058"
  uid: 53254c16-8383-45be-bf6d-abbd82fa009c
spec:
  clusterIP: 172.21.138.170
  clusterIPs:
  - 172.21.138.170
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: analyzer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: code-analyzer
    environment: dev
    language: python
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
