apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-service-dev","namespace":"mmjc-dev"},"spec":{"ports":[{"name":"redis","port":6379,"targetPort":6379}],"selector":{"app":"redis-cluster"},"type":"ClusterIP"}}
  creationTimestamp: "2025-06-16T13:57:37Z"
  name: redis-service-dev
  namespace: mmjc-dev
  resourceVersion: "10751200"
  uid: 8058278c-a1cd-4f87-ab41-4df4bf4025ec
spec:
  clusterIP: 172.21.37.105
  clusterIPs:
  - 172.21.37.105
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-cluster
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
