apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-dev
    meta.helm.sh/release-namespace: mmjc-dev
  creationTimestamp: "2025-07-31T07:18:54Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: milvus-mmjc-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-6.3.3
  name: milvus-mmjc-dev-etcd
  namespace: mmjc-dev
  resourceVersion: "22637733"
  uid: 84d7941f-b07f-40ee-9283-9ef357dddc02
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: milvus-mmjc-dev
      app.kubernetes.io/name: etcd
  serviceName: milvus-mmjc-dev-etcd-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: milvus-mmjc-dev
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: etcd
        helm.sh/chart: etcd-6.3.3
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: milvus-mmjc-dev
                  app.kubernetes.io/name: etcd
              namespaces:
              - mmjc-dev
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ETCDCTL_API
          value: "3"
        - name: ETCD_ON_K8S
          value: "yes"
        - name: ETCD_START_FROM_SNAPSHOT
          value: "no"
        - name: ETCD_DISASTER_RECOVERY
          value: "no"
        - name: ETCD_NAME
          value: $(MY_POD_NAME)
        - name: ETCD_DATA_DIR
          value: /bitnami/etcd/data
        - name: ETCD_LOG_LEVEL
          value: info
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://$(MY_POD_NAME).milvus-mmjc-dev-etcd-headless.mmjc-dev.svc.cluster.local:2379
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://$(MY_POD_NAME).milvus-mmjc-dev-etcd-headless.mmjc-dev.svc.cluster.local:2380
        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380
        - name: ETCD_AUTO_COMPACTION_MODE
          value: revision
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1000"
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster-k8s
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new
        - name: ETCD_INITIAL_CLUSTER
          value: milvus-mmjc-dev-etcd-0=http://milvus-mmjc-dev-etcd-0.milvus-mmjc-dev-etcd-headless.mmjc-dev.svc.cluster.local:2380,milvus-mmjc-dev-etcd-1=http://milvus-mmjc-dev-etcd-1.milvus-mmjc-dev-etcd-headless.mmjc-dev.svc.cluster.local:2380,milvus-mmjc-dev-etcd-2=http://milvus-mmjc-dev-etcd-2.milvus-mmjc-dev-etcd-headless.mmjc-dev.svc.cluster.local:2380
        - name: ETCD_CLUSTER_DOMAIN
          value: milvus-mmjc-dev-etcd-headless.mmjc-dev.svc.cluster.local
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "4294967296"
        - name: ETCD_HEARTBEAT_INTERVAL
          value: "500"
        - name: ETCD_ELECTION_TIMEOUT
          value: "2500"
        image: docker.io/milvusdb/etcd:3.5.18-r1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/bitnami/scripts/etcd/prestop.sh
        livenessProbe:
          exec:
            command:
            - /opt/bitnami/scripts/etcd/healthcheck.sh
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: etcd
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: peer
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /opt/bitnami/scripts/etcd/healthcheck.sh
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/etcd
          name: data
      dnsPolicy: ClusterFirst
      nodeSelector:
        ibm-cloud.kubernetes.io/worker-pool-name: milvus-pool
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: reserved
        operator: Equal
        value: milvus
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: milvus-mmjc-dev-etcd-6f58fb8487
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: milvus-mmjc-dev-etcd-6f58fb8487
  updatedReplicas: 3
