apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend-mmjc-test","namespace":"mmjc-test"},"spec":{"ports":[{"name":"http-frontend","port":80,"protocol":"TCP","targetPort":"frontend"}],"selector":{"app":"frontend-mmjc"}}}
  creationTimestamp: "2025-06-17T03:56:14Z"
  name: frontend-mmjc-test
  namespace: mmjc-test
  resourceVersion: "10885762"
  uid: b90b3f12-e4c9-42ff-91b9-57210bbdca66
spec:
  clusterIP: 172.21.55.212
  clusterIPs:
  - 172.21.55.212
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-frontend
    port: 80
    protocol: TCP
    targetPort: frontend
  selector:
    app: frontend-mmjc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
