apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/description: High-performance MCP Git-S3 Tools Server
    app.kubernetes.io/documentation: https://github.com/your-org/java-mcp-tool-s3git
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"app.kubernetes.io/description":"High-performance MCP Git-S3 Tools Server","app.kubernetes.io/documentation":"https://github.com/your-org/java-mcp-tool-s3git","deployment.kubernetes.io/revision":"1"},"labels":{"app":"mcp-git-s3-server","app.kubernetes.io/component":"api-server","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"mcp-git-s3-server","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"0.0.1-SNAPSHOT","component":"service"},"name":"mcp-git-s3-server","namespace":"mmjc-test"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":"http"},{"name":"https","port":8443,"protocol":"TCP","targetPort":"https"},{"name":"metrics","port":9090,"protocol":"TCP","targetPort":"metrics"}],"selector":{"app":"mcp-git-s3-server","app.kubernetes.io/component":"api-server","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"mcp-git-s3-server","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"0.0.1-SNAPSHOT"},"type":"ClusterIP"}}
  creationTimestamp: "2025-06-16T11:56:39Z"
  labels:
    app: mcp-git-s3-server
    app.kubernetes.io/component: api-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mcp-git-s3-server
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    component: service
  name: mcp-git-s3-server
  namespace: mmjc-test
  resourceVersion: "10730980"
  uid: b109de71-0337-48ed-b18d-35daa388581f
spec:
  clusterIP: 172.21.208.78
  clusterIPs:
  - 172.21.208.78
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app: mcp-git-s3-server
    app.kubernetes.io/component: api-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mcp-git-s3-server
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
