apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: milvus-mmjc-test
    meta.helm.sh/release-namespace: mmjc-test
  creationTimestamp: "2025-07-31T08:33:13Z"
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-8.0.17
    heritage: Helm
    release: milvus-mmjc-test
  name: milvus-mmjc-test-minio
  namespace: mmjc-test
  resourceVersion: "22654262"
  uid: 513d5bc7-a0f5-4559-b590-823c0997864e
spec:
  clusterIP: 172.21.138.210
  clusterIPs:
  - 172.21.138.210
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    release: milvus-mmjc-test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
