# ⚠️  WARNING: This is a TEMPLATE - NOT for production use
# All sensitive data has been replaced with placeholders
# Replace all <REPLACE_WITH_BASE64_ENCODED_*> values before applying
#
# Original: mmjc-dev/secrets/api-file-zip-s3-secrets.yaml
# Templated: Fri Oct 31 21:15:03 -03 2025
#
apiVersion: v1
data:
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: <REMOVED_CONTAINED_PLAINTEXT_SECRETS>
  name: api-file-zip-s3-secrets
  namespace: mmjc-dev
type: Opaque
