# ⚠️  WARNING: This is a TEMPLATE - NOT for production use
# All sensitive data has been replaced with placeholders
# Replace all <REPLACE_WITH_BASE64_ENCODED_*> values before applying
#
# Original: mmjc-dev/secrets/azure-openai-deployment-name-agents.yaml
# Templated: Fri Oct 31 21:15:03 -03 2025
#
apiVersion: v1
data:
  AZURE_OPENAI_DEPLOYMENT_NAME: <REPLACE_WITH_BASE64_ENCODED_AZURE_OPENAI_DEPLOYMENT_NAME>
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: <REMOVED_CONTAINED_PLAINTEXT_SECRETS>
  name: azure-openai-deployment-name-agents
  namespace: mmjc-dev
type: Opaque
