# ⚠️  WARNING: This is a TEMPLATE - NOT for production use
# All sensitive data has been replaced with placeholders
# Replace all <REPLACE_WITH_BASE64_ENCODED_*> values before applying
#
# Original: mmjc-dev/secrets/langfuse-init-config.yaml
# Templated: Fri Oct 31 21:15:03 -03 2025
#
apiVersion: v1
data:
  org_id: <REPLACE_WITH_BASE64_ENCODED_ORG_ID>
  org_name: <REPLACE_WITH_BASE64_ENCODED_ORG_NAME>
  project_id: <REPLACE_WITH_BASE64_ENCODED_PROJECT_ID>
  project_name: <REPLACE_WITH_BASE64_ENCODED_PROJECT_NAME>
  public_key: <REPLACE_WITH_BASE64_ENCODED_PUBLIC_KEY>
  secret_key: <REPLACE_WITH_BASE64_ENCODED_SECRET_KEY>
  user_email: <REPLACE_WITH_BASE64_ENCODED_USER_EMAIL>
  user_name: <REPLACE_WITH_BASE64_ENCODED_USER_NAME>
  user_password: <REPLACE_WITH_BASE64_ENCODED_USER_PASSWORD>
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: <REMOVED_CONTAINED_PLAINTEXT_SECRETS>
  name: langfuse-init-config
  namespace: mmjc-dev
type: Opaque
