apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow-test
    meta.helm.sh/release-namespace: airflow-test
  creationTimestamp: "2025-07-14T10:31:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.17.0
    component: triggerer
    heritage: Helm
    release: airflow-test
    tier: airflow
  name: airflow-test-triggerer
  namespace: airflow-test
  resourceVersion: "17792636"
  uid: 9105c5a2-61a7-4b2a-957a-654ffc5aaca3
