apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow-test
    meta.helm.sh/release-namespace: airflow-test
  creationTimestamp: "2025-07-14T10:31:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.17.0
    component: statsd
    heritage: Helm
    release: airflow-test
    tier: airflow
  name: airflow-test-statsd
  namespace: airflow-test
  resourceVersion: "17792631"
  uid: 33a9740f-4e9f-4158-852c-b1f299aa5585
