apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: airflow-test
    meta.helm.sh/release-namespace: airflow-test
  creationTimestamp: "2025-07-14T10:31:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.17.0
    heritage: Helm
    release: airflow-test
    tier: airflow
  name: airflow-test-pod-launcher-role
  namespace: airflow-test
  resourceVersion: "17792643"
  uid: 738b456c-551a-465c-9030-bf2cf9fdc6fd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - list
  - get
  - patch
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
