apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: airflow-test
    meta.helm.sh/release-namespace: airflow-test
  creationTimestamp: "2025-07-14T10:31:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.17.0
    heritage: Helm
    release: airflow-test
    tier: airflow
  name: airflow-test-pod-log-reader-role
  namespace: airflow-test
  resourceVersion: "17792644"
  uid: 9001ee93-31a5-4e0d-b3e7-ac4e0fd930a5
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
