apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app":"api-file-zip-s3","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"api-file-zip-s3","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"dev","component":"rbac","environment":"mmjc-dev"},"name":"api-file-zip-s3","namespace":"mmjc-dev"},"rules":[{"apiGroups":[""],"resources":["configmaps","secrets"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["pods"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2025-10-29T05:32:34Z"
  labels:
    app: api-file-zip-s3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-file-zip-s3
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: dev
    component: rbac
    environment: mmjc-dev
  name: api-file-zip-s3
  namespace: mmjc-dev
  resourceVersion: "54439538"
  uid: bcd922e2-a3e5-4c11-bc2a-e177005ff61d
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
