apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app":"api-zip-s3","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"api-zip-s3","app.kubernetes.io/part-of":"mcp-platform","app.kubernetes.io/version":"dev","component":"rbac","environment":"mmjc-dev"},"name":"dev-api-zip-s3","namespace":"mmjc-dev"},"rules":[{"apiGroups":[""],"resources":["configmaps","secrets"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["pods"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2025-10-27T06:32:11Z"
  labels:
    app: api-zip-s3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-zip-s3
    app.kubernetes.io/part-of: mcp-platform
    app.kubernetes.io/version: dev
    component: rbac
    environment: mmjc-dev
  name: dev-api-zip-s3
  namespace: mmjc-dev
  resourceVersion: "53774089"
  uid: 450cba4c-d184-44d4-bbb0-dbf9b102bca7
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
