apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate ConfigMaps from environment files
configMapGenerator:
  - name: s3-config
    envs:
      - s3-config.env
    options:
      labels:
        app.kubernetes.io/managed-by: kustomize
        config-type: s3

  - name: llm-config
    envs:
      - llm-config.env
    options:
      labels:
        app.kubernetes.io/managed-by: kustomize
        config-type: llm

  - name: database-config
    envs:
      - database-config.env
    options:
      labels:
        app.kubernetes.io/managed-by: kustomize
        config-type: database

  - name: application-config
    envs:
      - application-config.env
    options:
      labels:
        app.kubernetes.io/managed-by: kustomize
        config-type: application

# Generate Secrets (these should reference actual secret values)
# For production, use: External Secrets Operator, Sealed Secrets, or Vault
secretGenerator:
  - name: s3-credentials
    literals:
      - access-key=<REPLACE_WITH_S3_ACCESS_KEY>
      - secret-key=<REPLACE_WITH_S3_SECRET_KEY>
    type: Opaque

  - name: llm-api-keys
    literals:
      - azure-openai-api-key=<REPLACE_WITH_AZURE_API_KEY>
      - openai-api-key=<REPLACE_WITH_OPENAI_API_KEY>
    type: Opaque

  - name: database-credentials
    literals:
      - postgres-username=<REPLACE_WITH_POSTGRES_USER>
      - postgres-password=<REPLACE_WITH_POSTGRES_PASSWORD>
      - redis-password=<REPLACE_WITH_REDIS_PASSWORD>
    type: Opaque

# Common labels applied to all generated resources
commonLabels:
  managed-by: kustomize
  config-tier: common

# Namespace (can be overridden in overlays)
namespace: mmjc-test
