apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mcp-gateway-test","namespace":"mmjc-test"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mcp-gateway"}},"strategy":{"rollingUpdate":{"maxSurge":0,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"labels":{"app":"mcp-gateway"}},"spec":{"containers":[{"env":[{"name":"MCPGATEWAY_UI_ENABLED","value":"true"},{"name":"MCPGATEWAY_ADMIN_API_ENABLED","value":"true"},{"name":"HOST","value":"0.0.0.0"},{"name":"AUTH_REQUIRED","value":"false"},{"name":"JWT_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"JWT_SECRET_KEY","name":"mcp-gateway-jwt"}}},{"name":"BASIC_AUTH_USER","value":"admin"},{"name":"BASIC_AUTH_PASSWORD","valueFrom":{"secretKeyRef":{"key":"BASIC_AUTH_PASSWORD","name":"mcp-gateway-pwd"}}},{"name":"POSTGRESQL_HOST","value":"7bce9b8c-e602-4ae6-8a44-ad87cc332d96.c9v3nahd0oekcvsra2t0.private.databases.appdomain.cloud"},{"name":"POSTGRESQL_USERNAME","valueFrom":{"secretKeyRef":{"key":"POSTGRESQL_USERNAME","name":"postgresql-secret-test"}}},{"name":"POSTGRESQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRESQL_PASSWORD","name":"postgresql-secret-test"}}},{"name":"DATABASE_URL","value":"postgresql://$(POSTGRESQL_USERNAME):$(POSTGRESQL_PASSWORD)@$(POSTGRESQL_HOST):32337/mcp"}],"image":"ghcr.io/ibm/mcp-context-forge:0.6.0","imagePullPolicy":"Always","name":"gateway","ports":[{"containerPort":4444,"name":"gateway"}],"resources":{"limits":{"cpu":0.25,"memory":"1Gi"},"requests":{"cpu":0.125,"memory":"1Gi"}}}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}]}}}}
  creationTimestamp: "2025-08-07T06:59:24Z"
  generation: 18
  name: mcp-gateway-test
  namespace: mmjc-test
  resourceVersion: "54552474"
  uid: 51ead051-6763-4606-8876-95e6ff8b8774
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mcp-gateway
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-29T15:33:12+02:00"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: mcp-gateway
    spec:
      containers:
      - env:
        - name: MCPGATEWAY_UI_ENABLED
          value: "true"
        - name: MCPGATEWAY_ADMIN_API_ENABLED
          value: "true"
        - name: HOST
          value: 0.0.0.0
        - name: AUTH_REQUIRED
          value: "false"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET_KEY
              name: mcp-gateway-jwt
        - name: BASIC_AUTH_USER
          value: admin
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: BASIC_AUTH_PASSWORD
              name: mcp-gateway-pwd
        - name: POSTGRESQL_HOST
          value: 7bce9b8c-e602-4ae6-8a44-ad87cc332d96.c9v3nahd0oekcvsra2t0.private.databases.appdomain.cloud
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRESQL_USERNAME
              name: postgresql-secret-test
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRESQL_PASSWORD
              name: postgresql-secret-test
        - name: DATABASE_URL
          value: postgresql://$(POSTGRESQL_USERNAME):$(POSTGRESQL_PASSWORD)@$(POSTGRESQL_HOST):32337/mcp
        image: ghcr.io/ibm/mcp-context-forge:0.6.0
        imagePullPolicy: Always
        name: gateway
        ports:
        - containerPort: 4444
          name: gateway
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-07T06:59:24Z"
    lastUpdateTime: "2025-08-07T06:59:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-07T06:59:24Z"
    lastUpdateTime: "2025-10-29T13:33:18Z"
    message: ReplicaSet "mcp-gateway-test-6bdcbc6c9c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 18
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
