apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mermaid-validator-api","environment":"test","managed-by":"kustomize","version":"1.0.0"},"name":"mermaid-validator-api","namespace":"mmjc-test"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mermaid-validator-api","environment":"test","managed-by":"kustomize"}},"template":{"metadata":{"labels":{"app":"mermaid-validator-api","environment":"test","managed-by":"kustomize","version":"1.0.1"}},"spec":{"containers":[{"env":[{"name":"NODE_ENV","value":"test"},{"name":"LOG_LEVEL","value":"info"},{"name":"PORT","value":"8000"}],"image":"icr.io/mjc-cr/mjc-mermaid-validator:1.0.0-amd64","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/v1/health","port":"http"},"initialDelaySeconds":30,"periodSeconds":30,"timeoutSeconds":10},"name":"mermaid-validator-api","ports":[{"containerPort":8000,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/v1/health","port":"http"},"initialDelaySeconds":10,"periodSeconds":5,"timeoutSeconds":5},"resources":{"limits":{"cpu":"750m","memory":"768Mi"},"requests":{"cpu":"375m","memory":"384Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"volumeMounts":[{"mountPath":"/app/tmp","name":"tmp-volume"},{"mountPath":"/app/logs","name":"logs-volume"}]}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}],"restartPolicy":"Always","securityContext":{"fsGroup":1001,"runAsGroup":1001,"runAsNonRoot":true,"runAsUser":1001},"terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"tmp-volume"},{"emptyDir":{},"name":"logs-volume"}]}}}}
  creationTimestamp: "2025-09-12T03:37:07Z"
  generation: 8
  labels:
    app: mermaid-validator-api
    environment: test
    managed-by: kustomize
    version: 1.0.0
  name: mermaid-validator-api
  namespace: mmjc-test
  resourceVersion: "42009392"
  uid: 247e123a-4544-4edc-99ed-d96562d8e0bc
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mermaid-validator-api
      environment: test
      managed-by: kustomize
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-09-19T12:01:51-03:00"
      creationTimestamp: null
      labels:
        app: mermaid-validator-api
        environment: test
        managed-by: kustomize
        version: 1.0.1
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: test
        - name: LOG_LEVEL
          value: info
        - name: PORT
          value: "8000"
        image: icr.io/mjc-cr/mjc-mermaid-validator:1.0.17-llm-ready-amd64
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: mermaid-validator-api
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 750m
            memory: 768Mi
          requests:
            cpu: 375m
            memory: 384Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/tmp
          name: tmp-volume
        - mountPath: /app/logs
          name: logs-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp-volume
      - emptyDir: {}
        name: logs-volume
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-09-19T15:04:47Z"
    lastUpdateTime: "2025-09-19T15:04:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-09-12T03:37:07Z"
    lastUpdateTime: "2025-09-24T20:57:15Z"
    message: ReplicaSet "mermaid-validator-api-6c9b64bb6b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
