apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: milvus-mmjc-test
    meta.helm.sh/release-namespace: mmjc-test
  creationTimestamp: "2025-07-31T08:33:14Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: milvus-mmjc-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: milvus
    app.kubernetes.io/version: 2.5.15
    component: mixcoord
    helm.sh/chart: milvus-4.2.57
  name: milvus-mmjc-test-mixcoord
  namespace: mmjc-test
  resourceVersion: "22666145"
  uid: 94bf7e83-399d-4375-99c8-06d566970a24
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: milvus-mmjc-test
      app.kubernetes.io/name: milvus
      component: mixcoord
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: a80e1722486eb28b5e2525d3e8db24f05a42b2b261cae89820cf996c0fcc781e
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: milvus-mmjc-test
        app.kubernetes.io/name: milvus
        component: mixcoord
    spec:
      containers:
      - args:
        - milvus
        - run
        - mixture
        - -rootcoord
        - -querycoord
        - -datacoord
        - -indexcoord
        image: milvusdb/milvus:v2.5.15
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: metrics
          timeoutSeconds: 5
        name: mixcoord
        ports:
        - containerPort: 9091
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /milvus/configs/default.yaml
          name: milvus-config
          readOnly: true
          subPath: default.yaml
        - mountPath: /milvus/configs/user.yaml
          name: milvus-config
          readOnly: true
          subPath: user.yaml
        - mountPath: /milvus/tools
          name: tools
      dnsPolicy: ClusterFirst
      nodeSelector:
        ibm-cloud.kubernetes.io/worker-pool-name: milvus-pool
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: reserved
        operator: Equal
        value: milvus
      volumes:
      - configMap:
          defaultMode: 420
          name: milvus-mmjc-test
        name: milvus-config
      - emptyDir: {}
        name: tools
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-31T09:18:15Z"
    lastUpdateTime: "2025-07-31T09:18:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-31T09:18:15Z"
    lastUpdateTime: "2025-07-31T09:18:15Z"
    message: ReplicaSet "milvus-mmjc-test-mixcoord-74f8499f5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
