apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"po-mmjc-test","namespace":"mmjc-test"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"po-mmjc"}},"strategy":{"rollingUpdate":{"maxSurge":0,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"labels":{"app":"po-mmjc"}},"spec":{"containers":[{"env":[{"name":"DB_URL","value":"7bce9b8c-e602-4ae6-8a44-ad87cc332d96.c9v3nahd0oekcvsra2t0.private.databases.appdomain.cloud"},{"name":"DB_PORT","value":"32337"},{"name":"DB_USER","value":"ibm_cloud_971c0f4f_db43_4a27_9d6b_45d548902957"},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"DB_PASSWORD","name":"db-password-po"}}},{"name":"DB_NAME","value":"mmjc"},{"name":"AGENTS_SERVER_URL","value":"http://agents-mmjc-test.mmjc-test.svc.cluster.local:80/agent_langgraph/invoke"},{"name":"API_KEY_NAME","value":"API-Key"},{"name":"API_KEY","valueFrom":{"secretKeyRef":{"key":"API_KEY","name":"api-key-po"}}},{"name":"COS_ENDPOINT_URL","value":"https://s3.us-south.cloud-object-storage.appdomain.cloud"},{"name":"COS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"S3_ACCESS_KEY","name":"s3-access-key-tools"}}},{"name":"COS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"S3_SECRET_KEY","name":"s3-secret-key-tools"}}},{"name":"LOG_LEVEL","value":"INFO"},{"name":"MAX_THREADS","value":"10"},{"name":"COS_MAX_KEYS","value":"1000"},{"name":"API_TIMEOUT_SEC","value":"120"},{"name":"DEFAULT_ROLE","value":"BLOCKED"},{"name":"AIRFLOW_TOKEN_URL","value":"http://airflow-test-api-server.airflow-test.svc.cluster.local:8080/auth/token"},{"name":"AIRFLOW_URL","value":"http://airflow-test-api-server.airflow-test.svc.cluster.local:8080/api/v2/"},{"name":"AIRFLOW_USERNAME","valueFrom":{"secretKeyRef":{"key":"AIRFLOW_USERNAME","name":"airflow-secret-test"}}},{"name":"AIRFLOW_PASSWORD","valueFrom":{"secretKeyRef":{"key":"AIRFLOW_PASSWORD","name":"airflow-secret-test"}}}],"image":"icr.io/mjc-cr/mmjc-po:0.0.2","imagePullPolicy":"Always","name":"po","ports":[{"containerPort":8080,"name":"po-mmjc"}],"resources":{"limits":{"cpu":0.25,"memory":"1Gi"},"requests":{"cpu":0.125,"memory":"1Gi"}}}],"imagePullSecrets":[{"name":"all-icr-io-mmjc"}]}}}}
  creationTimestamp: "2025-06-17T03:51:41Z"
  generation: 19
  name: po-mmjc-test
  namespace: mmjc-test
  resourceVersion: "52926659"
  uid: 35846fda-8764-4866-8ad5-f1021712fb42
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: po-mmjc
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-08T13:10:15+03:00"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: po-mmjc
    spec:
      containers:
      - env:
        - name: DB_URL
          value: 7bce9b8c-e602-4ae6-8a44-ad87cc332d96.c9v3nahd0oekcvsra2t0.private.databases.appdomain.cloud
        - name: DB_PORT
          value: "32337"
        - name: DB_USER
          value: ibm_cloud_971c0f4f_db43_4a27_9d6b_45d548902957
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: db-password-po
        - name: DB_NAME
          value: mmjc
        - name: AGENTS_SERVER_URL
          value: http://agents-mmjc-test.mmjc-test.svc.cluster.local:80/agent_langgraph/invoke
        - name: API_KEY_NAME
          value: API-Key
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: API_KEY
              name: api-key-po
        - name: COS_ENDPOINT_URL
          value: https://s3.us-south.cloud-object-storage.appdomain.cloud
        - name: COS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY
              name: s3-access-key-tools
        - name: COS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_KEY
              name: s3-secret-key-tools
        - name: LOG_LEVEL
          value: INFO
        - name: MAX_THREADS
          value: "10"
        - name: COS_MAX_KEYS
          value: "1000"
        - name: API_TIMEOUT_SEC
          value: "120"
        - name: DEFAULT_ROLE
          value: BLOCKED
        - name: AIRFLOW_TOKEN_URL
          value: http://airflow-test-api-server.airflow-test.svc.cluster.local:8080/auth/token
        - name: AIRFLOW_URL
          value: http://airflow-test-api-server.airflow-test.svc.cluster.local:8080/api/v2/
        - name: AIRFLOW_USERNAME
          valueFrom:
            secretKeyRef:
              key: AIRFLOW_USERNAME
              name: airflow-secret-test
        - name: AIRFLOW_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AIRFLOW_PASSWORD
              name: airflow-secret-test
        image: icr.io/mjc-cr/mmjc-po:0.0.2
        imagePullPolicy: Always
        name: po
        ports:
        - containerPort: 8080
          name: po-mmjc
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io-mmjc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-17T03:51:41Z"
    lastUpdateTime: "2025-06-17T03:51:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-17T03:51:41Z"
    lastUpdateTime: "2025-10-08T10:10:20Z"
    message: ReplicaSet "po-mmjc-test-68dcb995d5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
